### ISSUE TITLE
Alternatively accept `_data.js` for metadata instead of plain JSON?

### ISSUE THREAD

**Issue by sgoumaz** [sintaxi/harp#103]
Our problem is, we need to make data in external JSON files (originating from elsewhere) available to Jade templates. (A reasonable use case I think.)

Right now it doesn't look possible within Harp (I would probably write a "pre-Harp" build step generating the ad-hoc `_data.json` files). The best way I see would be that we can optionally replace the `_data.json` with a `_data.js`, in which we'd load the external files with `require()` (and more generally do any simple preprocessing we need). Would that fit? If yes I'll be happy to submit the simple PR, if not alternative suggestions are welcome.

**Comment by barraq** [comment]
:+1:
