### ISSUE TITLE
Nesting Layouts

### ISSUE THREAD

**Issue by rambleraptor** [sintaxi/harp#145]
Forgive me if this is possible already.

It seems like it would be nice to have the ability to nest layouts. For example, in a blog, I may want a post layout that would have title and Disqus comments. That post layout would inherit from my main layout so the site retains its natural look.

**Comment by mrchief** [comment]
But then you get bitten by this: https://github.com/sintaxi/harp/issues/371

**Comment by mrchief** [comment]
> Hey, unfortunately you basically have to choose between Jade’s blocks / extends system or Harp’s implicity _layout / partial system.

Just learnt about [this](https://github.com/sintaxi/harp/issues/292#issuecomment-43951514)
