### ISSUE TITLE
Ability to bind ip address

### ISSUE THREAD

**Issue by shekhargulati** [sintaxi/harp#146]
Hello,

I want to use Harp with OpenShift but harp does not allow a way to bind ip address.Currently it only uses port. 

I want to do something like this

```
require('harp').server("_harp", { ip : process.env.OPENSHIFT_NODEJS_IP || "127.0.0.1", port: process.env.OPENSHIFT_NODEJS_PORT|| 3000})
```

 I got this working by changing Harp index.js

```

exports.server = function(dirPath, options, callback){
  connect.createServer(
    middleware.regProjectFinder(dirPath),
    middleware.setup,
    middleware.underscore,
    middleware.mwl,
    middleware.static,
    middleware.poly,
    middleware.process,
    middleware.fallback
  ).listen(options.port,options.ip ,  callback)
}
```

Thanks
Shekhar

**Comment by m-o-e** [comment]
Bump!

Can someone please fix/merge https://github.com/sintaxi/harp/pull/219 (adds '-i' argument to set bind address)?

It's rather stupid to include a network server that can not serve the network.
