### ISSUE TITLE
Build in Underscore to make data collections more versatile 

### ISSUE THREAD

**Issue by edrex** [sintaxi/harp#150]
Currently there isn't an obvious way to do some common operations with data objects:

 - Limit: how can I get the first 10 elements?
 - Sort by a particular field, reverse the order, etc.

Not sure how best to make them more versatile, but here are some ideas:

 - Put `var _  = require('lodash')` (or similar) in the Jade/EJS scopes.
 - Add a `_slug` or `slug` field to each object, in addition to using it as the key in the `data` collection, so if I convert to an array I can still generate a link.

One could then for example:

```jade
each post in _.sortBy(public.data, 'date').reverse().slice(0,10)
  li
    a(href="/#{post._slug}")= post.title
```

I recognize that there's a strong reluctance to add anything unnecessary to the interface, but some more versatile way of working with the collections seems to be needed.

**Comment by lunelson** [comment]
I made a PR to terraform to [expose lodash to templates](https://github.com/sintaxi/terraform/pull/109)

**Comment by spinscale** [comment]
I think we can close thise with the 0.20 release, which ships terraform that includes https://github.com/sintaxi/terraform/pull/109 ?

**Comment by kennethormandy** [comment]
You’re right @spinscale, thanks.

Thanks to @lunelson, Lodash is part of Harp as of v0.20.x. [More details are in the release blog post.](http://harpjs.com/blog/v0-20-0-node-5-compatibility)
