### ISSUE TITLE
compile --watch

### ISSUE THREAD

**Issue by stanch** [sintaxi/harp#152]
It would be very nice to have a `--watch` option for `compile` command, which would trigger recompilation on file changes (like _brunch_ has). Use-case: development environment where _harp_ is used to produce static assets for a loosely-coupled backend.

**Comment by starhawkhkk** [comment]
@stanch I'm not seeing why you can't integrate harp as middleware into your backend, where it then interprets files in backend/public realtime.

If you don't need minification, concatenation...etc., brunch is really an overkill.

**Comment by howardroark** [comment]
I would really like a `harp compile --watch` natured command available as well.  I really enjoy the nature of harp's convention vs configuration approach.  I would love to use it as the asset pipelines for other projects as well (especially with out-of-the-box CMS projects).

Using the harp server is not ideal in these cases as it causes the need to "bend" the setup of whatever you are using.  It would be much easier to just output compiled assets to a folder when changes occur.

I love the the harp web server itself, but it is more geared towards stand alone projects.  This case would be one where you were using another solution as your tempting system and you just want harp to handle all of the other assets.

**Comment by phrozen** [comment]
+1

Is any work being done to this feature? I would love this feature to work with mobile and desktop apps (phonegap, electron, etc...) while using Jade/Sass/Coffee and not compiling every single time! Also it would be amazing for decoupled frontends as the original case scenario.
