### ISSUE TITLE
Compile Errors to console

### ISSUE THREAD

**Issue by silentrob** [sintaxi/harp#153]
We currently send errors as html rendered to the view, but some setups and environments miss this and it would be nice to see or catch them in the terminal / console.
- This would be ideal for test runners during compile

**Comment by edrex** [comment]
Yes please! I think error reporting/surfacing is generally lacking throughout and would like to see/participate in a broad effort to improve it. Maybe a new tag?

**Comment by silentrob** [comment]
Wow, this is an old issue. Let me chat with @kennethormandy and @sintaxi and see if there is any low hanging fruit, or an easy way forward.
