### ISSUE TITLE
Harp installation faulty?

### ISSUE THREAD

**Issue by Cmacca** [sintaxi/harp#155]
Hello, I've tried a lot of stuff with my initial harp start up. Here's what I'm having trouble with:
1. sudo npm install -g harp
2. harp init myproj
3. harp server myproj

This for some reason does not display anything in my browser when I navigate to the specified port.

Anyone have knowledge of this error? 
Initially, I was getting an error from a 404 file of sorts that said the length or something was "null".

**Comment by gopirajum** [comment]
gopiraju@ubuntu:~$ sudo npm install -g harp
npm http GET https://registry.npmjs.org/harp

npm ERR! Error: failed to fetch from registry: harp
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/gopiraju/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "harp"
npm ERR! cwd /home/gopiraju
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: harp
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gopiraju/npm-debug.log
npm not ok

**Comment by sintaxi** [comment]
Your version of NodeJS is from March 2012. Any chance you can upgrade?
