### ISSUE TITLE
Harp compile --pretty

### ISSUE THREAD

**Issue by kevinsimper** [sintaxi/harp#169]
It would be nice if you could make applications like jade compile with option `pretty = true`;

Often when i am prototyping i use Jade because i need to do it fast, but clients often want it in plain css.

But the css from jade is by default not pretty.
`pretty = false`
![image](https://f.cloud.github.com/assets/1126497/1640617/2827828a-583e-11e3-87f7-c5d7e6cb3bf3.png)
`pretty = true``
![image](https://f.cloud.github.com/assets/1126497/1640621/45ebbaac-583e-11e3-9cfc-b842649f9d63.png)

**Comment by iamachimp** [comment]
I see this is an old issue. Does anyone know of a workaround? I just discovered harp and love it, but this sadly may be a deal breaker for me.

**Comment by ixley** [comment]
Not sure of any workarounds... I liked Harp but eventually found that
Middleman satisfied more needs for me than Harp was able to.

**Comment by sintaxi** [comment]
@ixley what specifically are your needs?

**Comment by ixley** [comment]
There were a few things – none of which were deal-breakers on their own, but added up, it felt like it maybe just the appropriate site generator for me. The lack of compile options was one small thing (made debugging trickier). The lack of clarity around whether a plugin for other languages would be coming was another. (I thought Jade was okay, but prefer Haml.) The lack of something like front matter was another little thing. (It wasn't a huge deal on its own, but felt like it would make maintenance on a site with multiple contributors more frustrating.) I am not a developer, and this was my first experience with a static site generator. It worked well out of the box, but for the reasons above, plus the fact I am also slightly more familiar with a Ruby-based environment,  Middleman felt like a slightly better fit for me right now.

**Comment by kennethormandy** [comment]
@iamachimp Here is one work-around: https://github.com/sintaxi/harp/issues/169#issuecomment-48372306 You can use another module for prettifying post-compile if that is helpful.

**Comment by iamachimp** [comment]
@kennethormandy 

Thank you, I'll look into it.

**Comment by ixley** [comment]
@sintaxi I realized that my comment was off-topic, and not so appropriate and so I'm deleting it for being unproductive. FWIW I didn't mean to bash Harp – I did appreciate it as a useful and easy to use site generator. I'm copying my other response here to make sure it goes to your inbox before I delete it, just in case the feedback is at all relevant to you. 

------
There were a few things – none of which were deal-breakers on their own, but added up, it felt like it maybe just the appropriate site generator for me. The lack of compile options was one small thing (made debugging trickier). The lack of clarity around whether a plugin for other languages would be coming was another. (I thought Jade was okay, but prefer Haml.) The lack of something like front matter was another little thing. (It wasn't a huge deal on its own, but felt like it would make maintenance on a site with multiple contributors more frustrating.) I am not a developer, and this was my first experience with a static site generator. It worked well out of the box, but for the reasons above, plus the fact I am also slightly more familiar with a Ruby-based environment, Middleman felt like a slightly better fit for me right now.

**Comment by ismatim** [comment]
I've just solved this with a task in Gulp and `gulp-sass` module with `expanded` option:

```
gulp.task('harp:post-compile:css', function() {
  return gulp
    .src(['src/dist/www/css/**/*.css'])
    .pipe(
      sass({
        outputStyle: 'expanded'
      }).on('error', sass.logError)
    )
    .pipe(
      autoprefixer({
        browsers: ['> 5%', 'last 4 versions'],
        cascade: false
      })
    )
    .pipe(gulp.dest('src/dist/www/css'))
});

```

**Comment by kevinsimper** [comment]
This can be solved with prettier now 😄

**Comment by bobsort** [comment]
> This can be solved with prettier now smile

how?
