### ISSUE TITLE
Link to Next/Previous objects in a JSON file

### ISSUE THREAD

**Issue by myk13** [sintaxi/harp#189]
I'm looking for a way to link to the 'next' and 'previous' objects in a JSON file.  

On IRC kennethormandy requested I log this as he has a recipe for it.

**Comment by mcbjam** [comment]
Hi. 

You are looking for 

articles.indexOf(current.source);

This is a link explain what you want to do with harp : 
http://www.raymondcamden.com/2014/02/26/Creating-NextPrevious-Links-in-HarpJS


One of my Website with Harp : http://buzz.mcbjam.com/
