### ISSUE TITLE
'harp' command is not found

### ISSUE THREAD

**Issue by theuiguru** [sintaxi/harp#20]
I've installed harp by using the command(s): 'npm install -g harp' and 'sudo npm install harp -g'. It looks like everything's installed within the npm.

But, whenever I enter 'harp', it says '-bash: harp: command not found'. Is it supposed to say that before making a project?

**Comment by kunzhangweb** [comment]
I had the same issue, and I solved it by creating a symbolic link as follow:
sudo ln -s /Users/myusername/.npm-global/bin/harp   /usr/local/bin

Then, when I typed harp -V again, it worked.
