### ISSUE TITLE
More comprehensive method to use *current* in Harp

### ISSUE THREAD

**Issue by ajmalafif** [sintaxi/harp#201]
I was reading http://harpjs.com/docs/development/current but I'm not sure where to put this piece below

```
{
  path: ["articles", "hello-world"],
  source: "hello-world"
}
```

is it in `_data.json` inside a folder or just under root's `_data.json`? 

I'm trying to add class `.active` for nav but couldn't figure out how

https://github.com/ajmalafif/harpline/blob/master/_shared/nav.jade

Tried with `current.path` too but still can't append `.active` in there. Help is greatly appreciated!

**Comment by LFeh** [comment]
Thanks guys!
