### ISSUE TITLE
Additional language plugin system

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/harp#209]
_Opened at @sintaxi’s request after a conversation with @heath  about LiveScript._

Harp needs to have a language system. We’re thinking any preprocessors beyond the ones we’ve already committed to would probably not be added to Harp’s core. Instead, we’d like it to [have a language system](https://github.com/sintaxi/harp/issues/110#issuecomment-26042311) for anyone to add preprocessors.

I believe there’s an API in mind, but no implementation started yet. It would probably stem from [terraform](https://github.com/sintaxi/terraform), which is Harp’s asset pipeline.

Potentially still in core:
- `.sass` polyfill (https://github.com/sintaxi/harp/issues/185)
- Enhanced EJS (#162)
- Handlebars (#60)
- Yoke

Requested so far:
- Ruby implementation of Sass (https://github.com/sintaxi/harp/issues/185)
- MultiMarkdown (As an option for front matter)
- TraceurScript (https://github.com/sintaxi/terraform/pull/17)
- LiveScript (#111, https://github.com/sintaxi/terraform/pull/10)
- Myth (#199) **+1**
- Wisp (#110) **+1**
- LitCoffee (https://github.com/sintaxi/harp/issues/156) **+2**
- OJ (https://github.com/sintaxi/harp/issues/154) **+1**
- Razor (https://github.com/sintaxi/harp/issues/141) **+1**
- ClojureScript (https://github.com/sintaxi/harp/issues/86) **+2**
- ECO (https://github.com/sintaxi/harp/issues/49) **+1**
- TypeScript (https://github.com/sintaxi/harp/issues/61) **+3**

**Comment by kevinSuttle** [comment]
+1 for Dust

**Comment by 4d47** [comment]
What's the status of this issue ?

**Comment by kevinsimper** [comment]
We need a way to declare what plugins you want to use for this to work.

It could either be global or local to the folder you are working in.

Method one:
the `harp.json` could contain a property that harp will try to require and put the content through.
Could be made easier by doing `$ harp enable sass markdown gulp-imagemin`
Benefits:
- declarative
- easy
Downsides:
- Have to do it everytime

Method two:
A proposed this to @sintaxi, but the idea is that there will be modules like `harp-sass`, and then harp will look at plugins installed that has `harp-` as a prefix and then load those. This will make it work global. The plugin would reqister an fileending and a function for the content to be passed though. 
Benefits: 
- Easy
- Fast
Downsides: 
- Version Incompatibles

**Comment by 4d47** [comment]
May I propose another option, something à la [Consolidate.js](https://github.com/tj/consolidate.js) where all preprocessors integration would still be in Terraform (mapping error to TerraformError etc) but activate only if module is actually installed (eg. you run `npm install LiveScript` in your project if you want LiveScript).
 
Benefit would be to work either per project or globally. It would also relief Terraform the need to choose/manage preprocessors versions.

There would still have the need to moderate modules that compete for file extensions (eg. different implementations of the same language) but that would still be an issue with other methods.

**Comment by kevinsimper** [comment]
@4d47 Seems like the best of those two, I think you are on the right path!

**Comment by Munter** [comment]
This project looks like it fits with the goals of https://github.com/jenius/accord

Have you thought about using that?
