### ISSUE TITLE
Question: _harp.json support with `harp server`

### ISSUE THREAD

**Issue by remy** [sintaxi/harp#213]
I've been switching back and forth between lib required version of Harp and out of the box Harp (i.e. `harp server`) and something that caught me out is renaming the Harp config file back and forth from `harp.json` and `_harp.json`.

Is there any reason why a single file name format for this config file couldn't be unified?

**Comment by sidonaldson** [comment]
Interesting this ticket is over a year old and this just caught me out too. Could this be a property of harp.json instead of being invisible magic?
`{frameworkMode: true}'

**Comment by skang404** [comment]
+1 same issue
