### ISSUE TITLE
Extend parent layout

### ISSUE THREAD

**Issue by kevinsimper** [sintaxi/harp#220]
Harp will use the _layout.jade if it exists, else it will use the parent _layout.jade.

How would i extend the current _layout.jade with the parent _layout?

So if i had a post folder, where i would like the layout to be a little different, but stil only maintain one main layout.

```
extend ../_layout
!= yield
h1 TEST
```

If i do this, it do use the parent layout, but TEST do not get printed out.

**Comment by stuartpb** [comment]
Shouldn't `echo {"layout": false} > _harp.json` disable `_layout.jade` being magic?
