### ISSUE TITLE
_harp.json in javascript file

### ISSUE THREAD

**Issue by singuerinc** [sintaxi/harp#226]
Hi, is it possible to embed a variable from _harp.json in a Javascript file? Like this:

``` javascript
var a = "<%= url %>";
```

Thanks

**Comment by Spone** [comment]
I'm also interested in this, but for SCSS/SASS files.

I'm using harp to create living style guides (see my [boilerplate](https://github.com/etaminstudio/hb-livingstyleguide)) and I'd like to avoid duplication (for data about icons, colors, fonts...).

For instance, for my icons I have something like this:

**icons.jade**
```jade
each code, icon in list
  p
    i(class="icon-#{icon}")
    code .icon-#{icon}
```

**_data.json**
```json
{
  "icons": {
    "list": {
      "check": "\e908",
      "close": "\e90b",
      "settings": "\e916",
      "share": "\e917",
      "star": "\e918"
    }
  }
}
```

I would love to have this in my **_icons.scss**:

```scss
@each $icon, $code in map-get($data, "icons") {
  .icon-#{$icon} {
    &:before {
      content: $code;
    }
  }
}
```

It could either be based on a SASS variable containing the metadata in the current scope, or a mixin giving access to it.

This way, I can edit structured data (the **_data.json** file) to compose my CSS files and their HTML documentation.

What do you think?

**Comment by singuerinc** [comment]
Feel free to reopen this issue if you want this feature. I don't think this is needed anymore.
