### ISSUE TITLE
"res.locals" are unavailable to view templates when using Express

### ISSUE THREAD

**Issue by dw2** [sintaxi/harp#227]
Consider the following code:

```
var express = require('express'),
    harp = require('harp'),
    app = express();

app.configure(function () {
    app.use(function (req, res, next) {
        res.locals.testvar = 'hello world';
        next();
    });
    app.use(express.static(__dirname + '/public'));
    app.use(harp.mount(__dirname + '/public'));
});

app.listen(9000);
```

The "testvar" variable is not available to view templates.

My guess is that Harp is writing over the locals variable to deliver it's own payload.

**Comment by mrchief** [comment]
Any update on this?

Apparently `app.locals` is also not available (to templates) due to the same reasons listed here.
