### ISSUE TITLE
Documentation of metadata overriding globals

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/harp#244]
This is something I tend to forget, so I wonder if others get tripped up on it. The docs for metadata state that when a page match is found that variables matched in _data.json will be available to the template:

> Because hello-world matches the filename, these variables will be made available in the hello-world.jade template when being served. 

But the fact that it can override a global may not be obvious. Does it make sense to call this out more? Should the globals doc also mention this feature?

**Comment by Spone** [comment]
This seems to be fixed, as the documentation now states: "*Any metadata in the harp.json file (or _harp.json) will be overwritten by the local metadata in the _data.json file.*"

See https://github.com/harp/harpjs.com/commit/d6cd0b8eb0a4a4041c08caa2467e38798a20d43e#diff-7b786bbf14f4d78184633f8bf4555320R42
