### ISSUE TITLE
Helper functions for jade

### ISSUE THREAD

**Issue by jamesknelson** [sintaxi/harp#248]
How hard would it be to allow harp.json to actually be a harp.js, where functions can be assigned to globals, as well as standard JSON - so that helper functions could be created? Is there an existing way to get helpers in a jade template (without placing the functions in the actual jade files)?

**Comment by alejonext** [comment]
+1

**Comment by suisho** [comment]
+1

**Comment by lunelson** [comment]
I made a PR to terraform to [expose lodash to templates](https://github.com/sintaxi/terraform/pull/109)

**Comment by sintaxi** [comment]
I dig it. Just merged into terraform. Will likely be in next release of harp.

**Comment by cfjedimaster** [comment]
So what exactly is being added - harp.hs? Or the helpers thing?
