### ISSUE TITLE
problems with dots in content filenames

### ISSUE THREAD

**Issue by samsonjs** [sintaxi/harp#250]
Use case: Porting an existing site / blog to harp. Renaming all my posts now would mean generating a bunch of Apache rewrite rules, blech.

I prefix my post filenames with the date using the dot as the date separator. e.g. "2014.02.15-this-is-my-post.md". This triggers the `terraform.helpers.outputPath` check for something like ".html.md". Since it's not there `outputType` doesn't know the result will be HTML and I get application/octet-stream as the content type instead of text/html.

Seems like the easy fix is for me to use ".html.md" instead of ".md". I don't love it, but that would be fine since it must be an edge case. However once I do that I can't access that post without the ".html" extension anymore, and I'm back at the Apache rewrite solution.

```
% curl -I localhost:9000/posts/2014.02.15-this-is-my-post | head -n 1
HTTP/1.1 404 Not Found
% curl -I localhost:9000/posts/2014.02.15-this-is-my-post.html | head -n 1
HTTP/1.1 200 OK
```

I hope this is a bug, but it could be expected behaviour. Please tell me it's a bug :smiley: 

(I'm actually not sure if this is a harp issue or a terraform issue)

**Comment by chalin** [comment]
To answer @sintaxi's [question](https://github.com/sintaxi/harp/pull/526#issuecomment-232821878): What we need for [angular.io](https://angular.io) is a version of harp that is dependent on a version of terraform that supports dots in `current`. Pretty much only this fix: https://github.com/sintaxi/terraform/commit/827e088d1dd74675eef6387ae8c542270b109099. 

I've tried running harp 0.21-pre (using terraform 1.x) but it reports an error when serving parts of angular.io, whereas 0.20.3 (with a manually patched terraform), doesn't. The error I get with 0.21-pre is:
```
Unexpected token: operator (>)
```
Might it be possible to create release terraform@v0.13.3 with just the dot fix and then update harp to use it? Maybe your tests will pass over this new config/version.

/cc: @naomiblack @kwalrath
