### ISSUE TITLE
Feature request: basic i18n support

### ISSUE THREAD

**Issue by kristoferjoseph** [sintaxi/harp#269]
# Add basic i18n support

First off, loving Harp!
Been wanting to add i18n support to my static html files and think I've come up with a simple way, but would like your feedback. If you can give me some pointers on how I will gladly add this to harp via a PR.
## Proposal:

add a data directory with nested locale directories:
### Input

```
myHarpProject/
| data/
| | en/
| | | _data.json => { "title": "Welcome" }
| | gb/
| | | _data.json => { "title": "Willkommen" }
| _layout.ejs
| _harp.json <= could be overridden by locale variables?
| index.ejs
```

Compiling the static site would output multiple versions of the pages nested in locale folders
### Output

```
myHarpProject/
| en/
| | index.html
| gb/
| | index.html
```
## Questions

Is this something you would want added to harp?
Should these locale variables override the harp.json values?

**Comment by AlvarezAriel** [comment]
This looks like a really nice feature.
What is the status?

**Comment by thomaslove** [comment]
There's a really great i18n project I used in a different project called i18n-node that could be used for translations perhaps? They way they lay their json files out works very well. Could be a source of inspiration? https://github.com/mashpie/i18n-node

**Comment by B7th** [comment]
+1. Also, would it be possible to read .yml as well?

**Comment by shibacomputer** [comment]
What happened with this?
