### ISSUE TITLE
Can’t visit IP while using multihost

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/harp#28]
If I visit the local IP and port on my computer or another device while using `multihost`, I get

`Local server does not support history.
Perhaps you are looking for <href='http://192.168.1.io:9966'>http://192.168.1.io:9966</a>.`

instead of my app. It works as expected while using `server`.

**Comment by rocketnova** [comment]
Has there been any progress on this? I am currently experiencing this bug.
