### ISSUE TITLE
Harp compiles Coffee files with "--bare" flag ?

### ISSUE THREAD

**Issue by kicksnarehat** [sintaxi/harp#281]
I just noticed that it looks like .coffee files are being compiled without the usual lexical-scoping:

http://coffeescript.org/#lexical-scope

So it looks like Harp is using the "--bare" flag. Have I done something strange with my environment or is this intentional? If the latter, can I turn this off and use the default CoffeeScript compilation?

Thanks!

**Comment by andrewboni** [comment]
Is there a way we can specify our CoffeeScript compile options?

**Comment by kennethormandy** [comment]
@andrewboni Not right now, no. We strive for convention over configuration, and our understanding was that this was the preferred default for CoffeeScript. We’re always open to feedback on that kind of stuff though
