### ISSUE TITLE
_data.yaml instead of _data.json

### ISSUE THREAD

**Issue by adius** [sintaxi/harp#290]
It would be really cool to be able to use a _data.yaml file instead of a _data.json file.
What do you think?

**Comment by Yajo** [comment]
I opened https://github.com/sintaxi/terraform/pull/141/ to fix conflicts in the original pr. Is there anything else I can do? I'm really looking forward to ger this in 😅 (I hate to write JSON).

**Comment by sintaxi** [comment]
Done. Just published `harp@0.29.0`. Thanks for the nice integration.
