### ISSUE TITLE
Harp + Grunt usemin task?

### ISSUE THREAD

**Issue by andrewboni** [sintaxi/harp#291]
I'd like to get Harp playing nicely with Grunt's `usemin` task so that I can concat, minify, and revision my static (`.js`, `.css`, image) assets.

I have it close to working, but am running into some issues.

First off, is this something that's:
- Doable?
- Recommended?
  Or is there a better way?

Here are my relevant pieces of code:
`Gruntfile.coffee`:

``` coffeescript
...
  grunt.registerTask "production", [
    "useminPrepare" # Prepare usemin (will scan _layout.jade for usemin markup)
    "concat"               # Concat JS and CSS files
    "uglify"                 # Minify JS
    "cssmin"              # Minify CSS
    "rev"                    # Revision assets by prepending a hash to the filename
    "usemin"             # Run the usemin task
    "harp:compile"
  ]
...
```

`usemin` and `useminPrepare` targets within `Gruntfile.coffee`:
(Notice that I'm using [usemin-patterns](https://github.com/bevacqua/usemin-patterns) to be able to run `usemin` on jade files [usemin expects html files].)

``` coffeescript
...
    useminPrepare:
      html: ["_layout.jade"]
    usemin:
      jade: "_layout.jade"
      options:
        assetsDirs: ["public"]
        patterns:
          jade: require('usemin-patterns').jade # Need this to run usemin on .jade files
...
```

`_layout.jade`:

``` jade
...
    link(rel="stylesheet", href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.min.css")
    link(rel="stylesheet", href="styles/onepage-scroll.css")
    //-<!-- build:css build/styles/compiled/main.min.css -->
    link(rel="stylesheet", href="styles/1.css")
    link(rel="stylesheet", href="styles/2.css")
    link(rel="stylesheet", href="styles/3.css")
    ...
    //-<!-- endbuild -->
...
    script(src="scripts/angular-scroll.min.js")
    script(src="scripts/jquery.onepage-scroll.js")
    //-<!-- build:js build/styles/compiled/main.min.js -->
    script(src="scripts/main1.js")
    script(src="scripts/main2.js")
    script(src="scripts/main3.js")
...
    //-<!-- endbuild -->
...
```

The main issues are that:
- The files, specified inside the `usemin` comments...

```
    //-<!-- build:js build/styles/compiled/main.min.js -->
    script(src="scripts/main1.js")
    script(src="scripts/main2.js")
    script(src="scripts/main3.js")
...
    //-<!-- endbuild -->
```

...don't exist when the `usemin` task gets run (although the `.coffee` counterparts do). Same goes for the `.styl` files and their `.css` counterparts.
- The `usemin` task injects HTML into the `_layout.jade` template, instead of jade syntax. This causes the concat, minify, and revision tasks to not work properly (see [here](https://github.com/bevacqua/usemin-patterns/issues/2) for more details)

Anyone have thoughts/suggestions? Much appreciated!

**Comment by peschee** [comment]
@kennethormandy Just stumbled upon this. Is the v1.0.0 roadmap still underway?
