### ISSUE TITLE
Jade blocks

### ISSUE THREAD

**Issue by leesus** [sintaxi/harp#292]
I'm building a simple site with Harp, and I'm using yield to pull in page content.  However, I'd like to use Jade blocks so that specific pages can output their own scripts into the layout.

At the moment, whatever I have in a block in my template just gets passed through as is into my layout.

For example:

```
// _layout.jade
html
  head
    title Hello, world
  body
    != yield
    div Random delimiter
    block scripts

// index.jade
h1 Hello, world
block scripts
  script(src='/some/script.js').
  div Not working
```

Outputs:

```
<html>
  <head>
    <title>Hello, world</title>
  </head>
  <body>
    <h1>Hello, world</h1>
    <script src="/some/script.js"></script>
    <div>Not working</div>
    <div>Random delimiter</div>
  </body>
</html>
```

As opposed to the intended result:

```
<html>
  <head>
    <title>Hello, world</title>
  </head>
  <body>
    <h1>Hello, world</h1>
    <div>Random delimiter</div>
    <script src="/some/script.js"></script>
    <div>Not working</div>
  </body>
</html>
```

Any ideas?

**Comment by seb2point0** [comment]
Hi @leesus. Could you share your solution please?

**Comment by leesus** [comment]
@seb2point0 It's been a while since I did this, hopefully you get the gist, pardon the pun... https://gist.github.com/leesus/eaa55b986a4fddd8320e
