### ISSUE TITLE
Request: asset folder helper

### ISSUE THREAD

**Issue by JSteunou** [sintaxi/harp#293]
Harpjs have an option to compile a project but does not transform assets path into correct relative path, which mean we have to have a webserver in order to view our compiled project.

It happens when you have articles, or posts within subfolders but with the main layout which is in root folder.

It could be nice to have a config option to set a public path in global var, but also tell harp to handle it as absolute or relative so it works flawless as server and as static.

The main idea behind that came when I start to write some documentation with Harpjs, but could not send a static copy by mail that could be read as it is.

**Comment by bubbleheadinc** [comment]
Hi. Has there been any update on this? Just started with Harp, and ran into this issue right away. Thanks

**Comment by kexoth** [comment]
Hello!

I'm also trying to use harp to build my static page on Github Pages & stuck with this issue.
In my opinion the relative path for the resources in `_layout.[ejs|jade]` should be calculated regarding the path of the `_layout` file in the filesystem, not regarding the file for which the layout is compiled.

Kex

**Comment by agibsen** [comment]
What's the status on this? It would be _really_ helpful with a {{root}} helper like in Zurb's Panini
[http://foundation.zurb.com/sites/docs/panini.html#root][http://foundation.zurb.com/sites/docs/panini.html#root)

**Comment by allergeek** [comment]
Hi, is there any way to avoid this construct? Thank you!
`<%- include ../../../_includes/_head %>`

**Comment by sintaxi** [comment]
@allergeek IIRC you can use and absolute path so `<%- include /_includes/_head %>` should also work.

**Comment by allergeek** [comment]
@sintaxi Thanx! I'm not sure why, but unfortunately it doesn't work for me. Do you think it on the EJS part?
This pretty much illustrates the problem: 
https://stackoverflow.com/questions/44499771/how-to-include-ejs-partials-using-absolute-path

I've seen a workaround with current.path, that renders a url for the proper environment. Checking just in case there's a simpler fix.

**Comment by allergeek** [comment]
![screen shot 2017-09-22 at 1 06 32 pm](https://user-images.githubusercontent.com/4365387/30762763-2090475a-9f98-11e7-8701-fff9d3613f07.png)

**Comment by sintaxi** [comment]
Oh crap, my bad. `include` is a template specific command that is built into the templating engine. Try using `partial` instead which is a harp sepcific mechanism. Its much more powerful and robust. 

http://harpjs.com/docs/development/partial
