### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by trapias** [sintaxi/harp#299]
Hello,
I'm new to harp - and of course LOVE it!
I had a problem with my Windows installation, but found a solution that maybe could help somebody else.
After running

```
 npm install -g harp
```

harp was not available everywhere on the system (command not found).
This because there's no harp.cmd in my %appdata%\roaming\npm directory: I then created a file named **harp.cmd** in there, with this code:

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\harp\bin\harp" %*
) ELSE (
  node  "%~dp0\node_modules\harp\bin\harp" %*
)
```

After this, I can launch "harp" anywhere from my CLI.
Hope this helps,
al.

**Comment by StingyJack** [comment]
IIRC, Its shortcut for "Current Working Directory"
