### ISSUE TITLE
Sass 3.3+ Maps not supported

### ISSUE THREAD

**Issue by electerious** [sintaxi/harp#329]
I get the following error when I try to use Sass maps:

> Sass -> CSS (error reading values after bandcamp) …

``` sass
$profiles: (
    bandcamp: #4e9bac,
    delicious: #248cff,
    facebook: #3b5998
);
```

I guess that Harp uses an old version of Sass? [Sass maps](http://viget.com/extend/sass-maps-are-awesome) are supported since version 3.3.

**Comment by jedfoster** [comment]
LibSass 3.1 is [now available](https://github.com/sass/libsass/releases/tag/3.1.0), complete with support for Sass maps. As of [now](https://github.com/sass/node-sass/releases/tag/v2.0.0-beta), node-sass includes the beta version of libsass 3.1.0. 

The version of node-sass included with Harp is _really_ old (in internet time.) I'd love to see Harp updated with the latest hotness. I'll try to put a PR together this week.

**Comment by jedfoster** [comment]
I have submitted a [pull request on terraform](https://github.com/sintaxi/terraform/pull/74) that updates node-sass to 2.0.0-beta.
