### ISSUE TITLE
I need "harp server" to serve .jade .coffee .less .xxx

### ISSUE THREAD

**Issue by kaven276** [sintaxi/harp#344]
sometimes, I feed browser with .jade .coffee .less ... files directly, no need for harp to compile to .js .css, but "harp server" will hide .jade .coffee .less, It's not desirable.

**Comment by arielkirkwood** [comment]
+1 for this request.

I'm trying to use [typeahead.js](https://github.com/twitter/typeahead.js) in a Harp project, and I'd like to use a client-side-loaded version of EJS to compile templates already being used by Harp for my typeahead.

**Comment by kevinsimper** [comment]
This is maybe not a use case for harp, if this is the case, every other http static server can be used!
