### ISSUE TITLE
List files in directory

### ISSUE THREAD

**Issue by ir-g** [sintaxi/harp#345]
Is it by any means possible to have a file which will automatically list all files in the current directory? This would be really helpful, as I simple don't have the time to keep on writing links, etc.

**Comment by lunelson** [comment]
is there an equivalent of the `_contents` object that tracks directories instead of or as well as files? I have a bunch of sub-pages in the form of `name-of-page/index.jade` — I do them as directories so they can have their own local `scss` and `js` files — and I'd like to have a table of contents (ideally, automatic) for them all at the root level  but `_contents` doesn't 'see' directories, only files.

**Comment by cfjedimaster** [comment]
Hmm, so I just tested this. Made a new Harp project. Added a subdirectory foo with index.html and a subdirectory under that called goo with no file. This is how Harp reports the contents in public:

    {
	"_contents": [
		"404.html",
		"index.html",
		"main.css"
	],
	"foo": {
		"_contents": [
			"index.html"
		]
	}
    }

As you can see, it doesn't show goo, and I think it should. If I add a file to goo:

    {
	"_contents": [
		"404.html",
		"index.html",
		"main.css"
	],
	"foo": {
		"_contents": [
			"index.html"
		],
		"goo": {
			"_contents": [
				"cat.html"
			]
		}
	}
    }

It does work correctly. So as long as your folders have files, then if you just access public, you can generate a directory listing well enough. Want a sample?

**Comment by lunelson** [comment]
Ah ok, I think I get it. It's not the `_contents` array I should look to (which is a file list, for a directory), but rather the 'contents' of the `public` object, which will contain keys for any directories that have files. That makes sense.

Sure I'd love to see a sample; but in fact I'm more interested in how you debugged the `public` object. Is there an equivalent to `var_dump` here?

**Comment by cfjedimaster** [comment]
See this recipe: http://harpjs.com/recipes/print-debugging

**Comment by lunelson** [comment]
ahhh yes of course. thanks :ok_hand:

**Comment by cfjedimaster** [comment]
@lunelson hope this helps - http://www.raymondcamden.com/2015/09/11/working-with-directories-and-harpjs

**Comment by lunelson** [comment]
Thanks for that. Indeed, I ended up doing this for first-level folders

```jade
ul: each value, key in public
    if (['_contents', '_data'].indexOf(key) == -1)
        li: a(href="/#{ key }")= key
```
