### ISSUE TITLE
HTML or Markdown in partial function JSON data -- not working

### ISSUE THREAD

**Issue by igregson** [sintaxi/harp#353]
Lots of incredible potential with Harp. Many thanks for all the awesome work that's already gone into it. 

One thing I've just come across, however, is that html or markdown used in json data with the partial function isn't being parsed as html... it's simply outputing plain text. Is this by design or a feature that can be implemented? 

Here's an example (using `jade`): 

**The Partial Call:**  

```
!=partial('my_partial', {title: "<b>Bolded Title</b>"})
```

**The Partial:**

```
h2 
  #{title}
```

**Output:**  

```
<b>Bolded Title<b>  // as viewed in the browser
```

As a use case for why I'm wanting this functionality, see [this post](http://engineering.lonelyplanet.com/2014/05/18/a-maintainable-styleguide.html) sharing about Lonely Planets "living" style guide.

**Comment by lawlesscreation** [comment]
I'm also interested if this is possible. I'm trying to get HTML into a partial in the same way:

```
<%- partial("my_partial", { content: "<p>" + lorem.sentence.short + "</p>" }) %>
```

or directly from the `_data.json` file:

```
      "sentence": {
          "short": "<p>Nullam a aliquet orci.</p>"
      }
```

Anyone know of a way to do this? Otherwise, I guess I can have the tag in the partial, but it would be nice to be able to parse HTML like `<strong>` or `<a>` inside the metadata.

**Comment by lawlesscreation** [comment]
D'oh... finally understood why this was not working for me. I had not escaped the local context correctly. I was using `<%= locals.content %>` instead of `<%- locals.content %>` in my partial.
