### ISSUE TITLE
Error when installing harp in terminal

### ISSUE THREAD

**Issue by woraperth** [sintaxi/harp#354]
The following error happens when installing harp via Mac OS Terminal using the following command:
    sudo npm install -g harp

---

> node-sass@0.9.3 install /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node build.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
/
node.js:815
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3
npm ERR! node-sass@0.9.3 install: `node build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@0.9.3 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "harp"
npm ERR! cwd /Users/woratana
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

---

I have tried remove and reinstalling NodeJS again. But the problem still persists

**Comment by bretonio** [comment]
I find that doing `cd ../` and then `chown -R myuser:myuser my-folder ` often works.
