### ISSUE TITLE
Jade nesting syntax #[ ]

### ISSUE THREAD

**Issue by callumflack** [sintaxi/harp#357]
Tiny thing but so useful. Just wondering if this will get merged into Harp at some point?

https://github.com/visionmedia/jade/issues/936

I took the time to look around for this in a previous issue but to no avail. Apologies if it's a dupe.

**Comment by jblanche** [comment]
Still no solution on this one ? 
I would love to use dynamic mixin calls but it's not available in terraform jade version :( 
http://stackoverflow.com/questions/24392055/jade-templates-dynamically-calling-a-mixin

**Comment by callumflack** [comment]
The web is typography. Good typography requires styling words and characters within blocks. I'm really feeling the pain of writing so many HTML spans inside Harp's jade. 

I don't have the ability to help out with this upgrade. Just (unhelpfully) re-upping the issue. I believe jade inlining will make a difference to designing and managing typography.
