### ISSUE TITLE
Multiple 404 pages

### ISSUE THREAD

**Issue by subhaze** [sintaxi/harp#358]
I've ran into an issue where more than one 404 page is needed.

I'm working on a multi-lang site and ran into a 404 where I hadn't yet setup some pages for the alternate lang and was shown an english 404 page which made me think, it'd be nice to have the ability to render different 404s per lang.

Currently I'm using the the first path segment to know what lang is expected and it's worked out very well, however, the 404 (from `current.path`) indicates it's at the root even though the actual URL has more segments.

I was curious if you all would be willing to allow 404 pages within subfolders so that they could be customized based on the current section of the site when needed or provide the real path on 404 pages? Though I'm thinking the latter would be a BC breakage...

Thanks!

**Comment by victorsegall** [comment]
This looks like part of i18n on #269, and could overlap with #225 #261 and #160.

What all of these share is a desire for a more complete routing for HTTP statuses. There are many cases where the content payload of a non-HTTP-200 response should be site-branded HTML, and all of the given issues are describing individual cases of that set.
