### ISSUE TITLE
Using current.source as a key breaks when compiling

### ISSUE THREAD

**Issue by djensen47** [sintaxi/harp#369]
I have this as a layout template in a subdirectory:

```
extends ../_layout.jade

block content
  h1 
    = public.issues._data[current.source].title
    | &nbsp;
    small= public.issues._data[current.source].date
  .issue
    != yield
```

I'm keeping all of my titles and dates in the issues/_data.json file so that they can be re-used for both lists and the page itself. This works fine when running the static web server but not during compilation.

Here's the compile error:

```
{
  "source": "Jade",
  "dest": "HTML",
  "filename": "project/public/issues/_layout.jade",
  "lineno": 5,
  "name": "TypeError",
  "message": "Cannot read property 'title' of undefined",
  "stack": "extends ../_layout.jade\n\nblock content\n  h1 \n    = public.issues._data[current.source].title\n    | &nbsp;\n    small= public.issues._data[current.source].date\n  .issue\n    != yield\n\n"
}
```

I tested outputting `current.source` and it writes out the expected value. I'm not sure what's going on here.

**Comment by davethegr8** [comment]
I'm not sure if it's worth reopening this bug, but I just ran into this issue with the CascadiaJS site.

https://github.com/cascadiajs/2015.cascadiajs.com/commit/12e191ba8b957bb99f076b16fdc82c1901518036

We're trying to conditionally include a partial for our news/blog.
