### ISSUE TITLE
Partial not included in top level layout in subdir files

### ISSUE THREAD

**Issue by djensen47** [sintaxi/harp#371]
I have, what I think is, a typical structure for issues or posts

```
root
|--public/
    |--_layout.jade
    |-- index.jade
    |-- partials/
    |-- issues/
        |-- _layout.jade
        |-- issue-1.md
```

If I include a partial in the top level _layout, it will be included when I view index. However, when I view /issues/issue-1 the partial is not included.

The partial I'm included is as such

```
!= partial('partials/_signup')
```

I've tried `!= partial('/partials/_signup')` and it does not work.

As a test, I tried `!= partial('../partials/_signup')` and it will work in the subdirs but not the top level files.

**Comment by mrchief** [comment]
Any update on this? I'm bitten by it too.

@djensen47 Thanks for the workaround!

**Comment by mrchief** [comment]
Unfortunately, the workaround doesn't work if you have another level of nesting

```
root
|--public/
    |--_layout.jade
    |-- index.jade
    |-- partials/
    |--categories
      |-- index.md  <- partials don't resolve for this guy
      |-- issues/
        |-- _layout.jade
        |-- issue-1.md
```

**Comment by lmcorreia** [comment]
Check if this can solve your problem: https://github.com/sintaxi/harp/issues/529#issuecomment-224025442
