### ISSUE TITLE
Feature Request: whitelisting folders that begin with _ and should be served either

### ISSUE THREAD

**Issue by teamgroove** [sintaxi/harp#373]
It would be awesome if the options/config would allow whitelisting of special folders that are historically named with an _underscore but really can't be changed. I have 5 portals that would require the main asset-folder to be named: "_assets". This folder needs to be served - even when it uses a _. 
I'm stuck here. I think a whitelisting-config would be the only unintrusive way. Switching such sites to harp ain't possible without rewiring everything else around these sites. it's a big problem changing that folder-name. i just can't do it, there are living links and shared assets to other sites.

**Comment by andrewplummer** [comment]
I would like to see this as well. Here's my use case:

Harp doesn't provide any bundling/importing of Javascript. This is fine for me, I've set up a uglify task when I compile. However, when running the harp server as a development server, it makes a lot of sense to require all the raw Javascript files in separate `<script>` tags and then bundle on compile. I do this in a lot of other different environments. 

There will be some private things when developing that will get bundled together on compile, but I don't think it makes sense to 404 disallow them when developing. I understand the reasoning of course -- harp is also a production server as well, and that's fine. But people with a develop -> compile workflow are going to have different needs so I think it's alright to break convention as an option.

**Comment by leitchst** [comment]
Hi Andrew,

It struck me that you could create a snippet for including your js files which links to the bundle when environment=production and otherwise includes the raw files.

I might be missing something here, though...

**Comment by andrewplummer** [comment]
Sorry I'm still a bit new to Harp... do you have an example of a "snippet"?

**Comment by leitchst** [comment]
Sorry, I meant partial.

So assume you have a _layout.ejs.  In there have <%- partial("_scripts")%>

Then in _scripts.ejs:
````
<% if ( environment = production) { %>
    <script href="bundle.js">
<% }
else {
        <script href="script1.js">
        <script href="script2.js">
        ...
} %>

(Consider that pseudo-code!)

Alternatively you could embed the conditional in the layout file, or conditionally include different partials.

Hope that makes sense (sorry for errors, I'm on my iPad...)

S

**Comment by andrewplummer** [comment]
That's all good but the problem is that script1.js and script2.js will be exported on compile then, no? In keeping with the conventions my JS "partials" (or "modules" for lack of a better word) I've labeled "_script1.js" etc because they aren't meant to be public-facing...

**Comment by leitchst** [comment]
Yeah, that will stop them being served, so you'd probably have to make them accessible so they work in dev.
They'd be present and accessible in prod, but not linked to.  You could add another post compile task to delete the raw scripts.

**Comment by andrewplummer** [comment]
Ah right. That's what I was kind of trying to avoid. Anyway thanks... true cleaning after compile is an option too...

**Comment by andrewmfiorillo** [comment]
So I am trying to use Harp to "multiserve" a bunch of Sphinx documentation websites, but Sphinx is very particular about keeping all of the built static files in a `_static` directory (and automatically pointing references there). I'm working on a small modification to Harp that creates an internal `helpers.shouldIgnore` function which looks at the `harp.json` file for prefixes to ignore, and defaults to the  convention used in `terraform.helpers.shouldIgnore`. I personally prefer the convention of ignoring folders that start with a `.` instead of an `_`, but this seems easy to fix with an optional configuration.

Would this be a reasonable solution?
