### ISSUE TITLE
Post limit

### ISSUE THREAD

**Issue by edwardessing** [sintaxi/harp#389]
Hey all, really really happy with harp so far. I'm namely a designer and most of my dev experience is with php so forgive me if I'm asking a dumb question :|

I'm creating a blog and I'd like to be able to limit the amount of posts per page or perhaps even integrate an endless scroll system...hope that makes sense

Thanks!

**Comment by kennethormandy** [comment]
Hope that’s still working out for you, we’ve also used that approach with success in the past. :)
