### ISSUE TITLE
globals not available when compiling

### ISSUE THREAD

**Issue by opichon** [sintaxi/harp#398]
When compile the site, globals are not available. They are rendered as empty strings or "undefined".
This seems to be the opposite of bug #333.
The local variables defined in _data.json are ok when compiling.
The globals are, of course, working when using harp serve.
I use a jade template.

**Comment by sintaxi** [comment]
can you create a failing test that demonstrates this problem?

**Comment by jdcauley** [comment]
What is your file tree?

**Comment by opichon** [comment]
I am sorry, I cannot seem to reproduce the issue with the latest versions of node and harp.js.
