### ISSUE TITLE
Change the markdown package 

### ISSUE THREAD

**Issue by ionm** [sintaxi/harp#401]
Is there an easy way of changing the markdown package that harp.js uses? I would like to use something like https://github.com/markdown-it/markdown-it

thanks.

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue.

Harp is made to avoid configuration, so if you need advanced options or changes, it’s not always the right choice. You could customize Harp’s preprocessor engine [Terraform](https://github.com/sintaxi/terraform) if you’d like, though.

We’ve been happy with Marked and plan on sticking with it for the immediate future.
