### ISSUE TITLE
Using Harp w/ Express and middleware

### ISSUE THREAD

**Issue by arxpoetica** [sintaxi/harp#402]
I'm trying to do the URI middleware feature explained on [this page](http://bengourley.co.uk/using-stylus) using Express and Harp, but somehow the middleware is not getting used.

Example:

```
app.use(stylus.middleware({
	src: __dirname,
	compile: function(str, path) {
		return stylus(str).define('url', stylus.url({
			paths: [__dirname + '/public'],
			limit: 10000
		}));
	}
}));
```

What am I doing wrong?

**Comment by kevinsimper** [comment]
It depends on the order of middlewares, if harp is before it will properly not reach it.

**Comment by arxpoetica** [comment]
I've tried both ways. I tried it *after*, and it's not attaching. But duly noted.

**Comment by arxpoetica** [comment]
https://gist.github.com/arxpoetica/d4c1888a5df4c8b4e4bd

**Comment by arxpoetica** [comment]
Also, this: 
![image](https://cloud.githubusercontent.com/assets/111424/6115758/e1bd6670-b075-11e4-9678-80d0c1c93052.png)

**Comment by arxpoetica** [comment]
Also this: 
![image](https://cloud.githubusercontent.com/assets/111424/6115787/21bdc38c-b076-11e4-8426-1c63a55eaf62.png)

**Comment by kevinsimper** [comment]
What does happen?

**Comment by kevinsimper** [comment]
Have you tried fixing the error?

**Comment by arxpoetica** [comment]
Dammit, my bad. URI stylus middleware still doesn't work, but I was conflating this issue w/ another one (sorry for the misleading confusion). I'm deleting my comment above.

**Comment by arxpoetica** [comment]
Anyway, to answer your question, literally nothing happens.

Expected behavior, something that looks like the following:

```
background-image: url(data:image/gif;base64,...);
```
actual behavior:

```
background-image: url('img/logo.png');
```

**Comment by kevinsimper** [comment]
That is not something about harp, 

and can not debug it without looking it closer what it actually do, try making an example only with stylus and not use harp.

**Comment by arxpoetica** [comment]
I see your point (though I'm not convinced it's unrelated to Harp)—I'll try that tack and let you know.

**Comment by sintaxi** [comment]
@arxpoetica what are your reasons for using the stylus middleware as well as harp (which provides stylus support)?

**Comment by arxpoetica** [comment]
@sintaxi stylus has advanced and optional features which are setup through middleware. Read the link I included in main post, which I'll include here for convenience: http://bengourley.co.uk/using-stylus I'm trying to set up the advanced `url()` data URI mixin. See also http://learnboost.github.io/stylus/docs/functions.url.html

This doesn't come out of the box. It has to be set up.

**Comment by arxpoetica** [comment]
Closing unless I can verify that it's not just a stylus/express issue.
