### ISSUE TITLE
Export notFound middleware

### ISSUE THREAD

**Issue by santervo** [sintaxi/harp#407]
I use harp mounted in Express application. I also want harp to respond to non existing resources with the default 404.jade, so I've used harp notFound middleware to achieve that:

```
var harpMiddleware = require("harp/lib/middleware");
app.use(harpMiddleware.notFound);
```

This feels hacky though as feature is undocumented. Could the notFound middleware be exported as part of main harp object?

**Comment by kennethormandy** [comment]
Hey! Thanks for opening an issue. The goal is to get the Harp `404.md`, `404.jade`, `404.ejs` or `404.html` file to be the 404 page in Express? If you (or anyone else) feel like you know how to make that work by default, I think we’d accept a pull request for it.

**Comment by santervo** [comment]
I was just thinking of exposing the notFound middleware (and documenting it) so that someone using it (like me) would not be in risk of app breaking by relying on app internals. I'll make a PR
