### ISSUE TITLE
Add .js custom extension for files (eg: xxxx.xml.ejs works, but xxxx.js.ejs does not)

### ISSUE THREAD

**Issue by dwarcher** [sintaxi/harp#410]
I'm trying to have harp generate a data feed as a static JS file - as mentioned in the docs, you can do this for .XML files, but trying to do this with a .JS doesn't work. Harp gives it a .js.html extension instead of just .js.

**Comment by dwarcher** [comment]
Hi guys, just wanted to check on this issue - I'm happy to submit a pull request and fix it myself if you could give me a little hint as to where to look to fix it. Is this a terraform issue or a harp issue?

**Comment by kennethormandy** [comment]
Hey, thanks for opening and issue first. I’m not sure if I understand the feature you’re proposing. Can you give an example of the kind of file that you’d to write in EJS and output as JS? Thanks!

**Comment by dwarcher** [comment]
The docs seem to imply that you can give any file a custom file extension by adding it before the .ejs part (http://harpjs.com/docs/development/ejs under 'managing file extension'). My main use case is to be able to do some really basic templating in JS files. So, for instance I may want to store my Facebook API key in my harp.json so that I can easily change it for different environments. Another case is to be able to output some of my metadata from my pages into a JS file to make it available to front-end javascript code. For example, lets say I want to provide an interface that lets people sort and filter blog posts on their meta data using javascript.

A gross example:

// blog-data.js.ejs
// output all blog data to front end javascript
var blogData = <%- JSON.stringify(public.blogs._data) %>;

I realize that you can do this using a <script> tag in your main template files, but there have been cases where being able to have a shared .js file is a better solution.

**Comment by matteo-bombelli** [comment]
I noticed if it is used any another extention (i used .scriptjs, but also '.pippo', '.php' ecc) it works, but in the template you have to use


        <script src="/js/main.scriptjs" type="text/javascript"></script>

This solution seems to work (i need to test it on older browsers)... but it is really preferred to use '.js'...

The reason to use ejs, for me, is to pass varables and to import different js in one js, cause i'm creating a framework

thanks!
