### ISSUE TITLE
Express 4 support 

### ISSUE THREAD

**Issue by isaacrg** [sintaxi/harp#412]
It has been announced that Express 3.x support will be ending soon. Is there currently solution to use Harp in Express 4?

**Comment by kennethormandy** [comment]
Personally, my experience is only with 3.x. If there’s changes that need to be made to fix Harp for Express 4 while maintaining compatibility with 3.x, we’d be happy to accept a pull request for that. If it’s more of a documentation issue, [that might be fixed now](https://github.com/harp/harpjs.com/commit/3cd2a1da744a53b7ac4dc194c96eaef6dfdd67c7)?

**Comment by isaacrg** [comment]
@kennethormandy After some testing, it appears that it is fixed. That example works fine, and it resolves my one fear about moving to Express 4. Thanks.
