### ISSUE TITLE
Not seeing Harp app at custom domain

### ISSUE THREAD

**Issue by i41** [sintaxi/harp#414]
I can't see my app at a custom domain. `harp.json` looks like this:

    {
	    "domains": ["posthorse.net", "www.posthorse.net"],
	    "globals": {
		"etc": "etc",

		"stylesheets": [],
        	"javascripts": []
	}
}

posthorse.net is showing the Harp 'project not found' screen, so looks like DNS is configured correctly.

**Comment by silentrob** [comment]
Did you re-publish the application after you updated the harp.json file?

**Comment by i41** [comment]
Yes. Have republished. 

In fact, have never changed harp.json after first publish — and the app was previously visible at posthorse.net.

**Comment by victorsegall** [comment]
"www.posthorse.net" is working while "posthorse.net" is not.

**Comment by i41** [comment]
Neither are working on my machine. www.posthorse.net is pointing to Gandi (the DNS provider) and posthorse.net is pointing to the 'project not found' on Harp page.

**Comment by victorsegall** [comment]
Ah, so it is. My mistake.

**Comment by kennethormandy** [comment]
Hey @i41, sorry for the trouble. On the dashboard, do you mind telling me if the app listed as _posthorse.harp.io_ or as _posthorse.com_? Ex. how the _harpjs.com_ is listed as _harpjs.com_ and not _harpjs.harp.io_:

![screen shot 2015-02-27 at 1 27 02 pm](https://cloud.githubusercontent.com/assets/1581276/6421484/592a51a2-be84-11e4-814f-5d574009c699.png)

**Comment by i41** [comment]
@kennethormandy Because of a weirdness in the way I was compiling, the harp.json file was being blown away. Thanks for the help!
