### ISSUE TITLE
Special Characters interfere with HTML

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/harp#42]
Using special characters in Jade or Markdown causes the HTML file to end a few characters early. This can cause a loose `</` to show up, rendered on the page, prevent tags from closing, etc.

This is possibly a duplicate of issue #40.

**Input**

``` jade
!!!
html(lang="en")
    head
        meta(charset="utf-8")
        title= globals.title
    body
        h1 Should’t “Do This” & more…
```

**Expected Output**
(Line breaks are for readability, the HTML compression is working fine.)

``` html
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Harp</title></head>
<body><h1>Should’t “Do This” & more…</h1>
</body>
</html>
```

**Actual Output**

``` html
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Harp</title></head>
<body>
<h1>Should’t “Do This” & more…</h1>
```

If you don’t use the proper characters and reference the special characters instead, the output is as you’d expect:

``` html
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Harp</title></head>
<body><h1>Should't "Do This" &amp; more&hellip;</h1>
</body>
</html>
```

**Comment by HoborgHUN** [comment]
The issue still exists for me now.
When trying to render “Iñtërnâtiônàlizætiøn”, the rendering stops after `</b` inside `</body>`
