### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/harp#420]
I'm looking at Jekyll this week and one of the big things I see it has that Harp does not is the ability to add plugins. Specifically - you can do stuff like this:
- loop over data 
- for each item, make a new file

The example I saw got all the unique "tag" values from the data and created files at /tag/{x} populate with the items that matched those tags.

**Comment by isaacrg** [comment]
@cfjedimaster Have you seen issue #209?

**Comment by cfjedimaster** [comment]
I had - but I had forgotten about it. Seems like we can close this maybe. The other issues seems to focus on other languages, but I really want to be sure it is more than just that, but also the 'process' of Harp, ie, do this when scanning so you can add more files, etc.
