### ISSUE TITLE
compile problem in 0.15.2

### ISSUE THREAD

**Issue by cardeo** [sintaxi/harp#422]
After updating from harp 0.14.0 to 0.15.2 I'm getting parse errors on my EJS files when I try to compile

**Comment by kennethormandy** [comment]
Hey Matt, did this turn out to be okay?

**Comment by cardeo** [comment]
Yeah just ended being a syntax error on my end, did you guys increase the
strictness in the latest version?

**Comment by kennethormandy** [comment]
No, Harp v0.14.0 and Harp v0.15.2 were both using EJS v1.0.0, I don’t think there should have been any changes there. Do you happen to remember what the error was?

**Comment by cardeo** [comment]
I was simply missing some = signs in my code, so like <class "span12" >

Once I fixed those up it compiled no problem. The actual error was really
generic, I think "parse error" then printed an escaped ejs page

In 14 it would compile with the errors but with 15 they were caught and
compiler failed until I fixed them

**Comment by cardeo** [comment]
Hey Kenneth,

Anything important I need to know for tonight? What time would you like me
there? 6ish or 6:30 when the doors open?

Thanks

Matt


On Tue, Mar 10, 2015 at 7:55 PM, Matt Lambert <info@cardeo.ca> wrote:

> I was simply missing some = signs in my code, so like <class "span12" >
>
> Once I fixed those up it compiled no problem. The actual error was really
> generic, I think "parse error" then printed an escaped ejs page
>
> In 14 it would compile with the errors but with 15 they were caught and
> compiler failed until I fixed them
> On Mar 10, 2015 7:03 PM, "Kenneth Ormandy" <notifications@github.com>
> wrote:
>
>> No, Harp v0.14.0 and Harp v0.15.2 were both using EJS v1.0.0, I don’t
>> think there should have been any changes there. Do you happen to remember
>> what the error was?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sintaxi/harp/issues/422#issuecomment-78186983>.
>>
>


-- 
Learn the easiest way to develop Bootstrap themes at: http://bit.ly/1ALMzXA

**Comment by kennethormandy** [comment]
Hey Matt! Send you an email.
