### ISSUE TITLE
Gzip compression

### ISSUE THREAD

**Issue by ghost** [sintaxi/harp#423]
As far as I can tell, there is no gzip compression used when serving the files. 

Are there any plans to implement this?

**Comment by silentrob** [comment]
This was something we had on deck and it didn't make it into the last release. I'm confident it will make it into the next one.

**Comment by mrmaxon** [comment]
Good to know. Thanks for the good work!

**Comment by yunspace** [comment]
+1 I'm currently working around this by using CDN such as Cloudlfare which provides gzip. But if Harp web server provide gzip out of box that would be awesome.

**Comment by valtido** [comment]
any news on this?
