### ISSUE TITLE
npm install -g harp on windows 7 error

### ISSUE THREAD

**Issue by MakiMark** [sintaxi/harp#425]
I have everything installed on my windows maschine: (ruby, compass and nodejs) and now I wanted to install the local webserver harp but i get the following errors (Please see pic below) can someone please help? Thanks a lot.

![error](https://cloud.githubusercontent.com/assets/11501730/6665455/05dc2bca-cbda-11e4-96ef-a12ef6054a99.png)

**Comment by silentrob** [comment]
This might sound like a crazy question, but where you online when you ran that command? It looks like you were unable to connect to github.com to pull in the remote repo.

**Comment by btkarthick** [comment]
I am also getting exactly the same error!!!

![harp-install-error](https://cloud.githubusercontent.com/assets/6745891/7064675/49ed810e-dece-11e4-836f-8ffb93432b3d.jpg)

**Comment by kennethormandy** [comment]
Ah I think the problem might be with using the GitHub URLs for dependencies when GitHub is down. We should be able to fix this to some degree. If you try the same thing again later on it should work.

**Comment by dogancelik** [comment]
@MakiMark, @btkarthick
This problem can be fixed by installing [MsysGit](https://msysgit.github.io/) and cleaning `npm-cache`!
Don't forget to put *git* in PATH.

**Comment by ksaff** [comment]
I encountered the same issue. Git must use a port that's blocked by the firewall I'm behind, as replacing `git://` with `https://` allowed me to clone the repo. Can this be changed somewhere?
