### ISSUE TITLE
Shared functions for EJS files?

### ISSUE THREAD

**Issue by dwarcher** [sintaxi/harp#429]
Not sure how possible this is, but it would be nice if there was a way to share functions between several partials in EJS. Currently all variables seem to be sandboxed to their particular partial, so there's no way to share functions between several files. It would be great if I could write some utility functions and share them across all the templates in my site, without having to copy and paste them into each partial.

**Comment by Ore4444** [comment]
e.g.
```
ejs.filters.last = function(obj) {
  return obj[obj.length - 1];
};
