### ISSUE TITLE
Simple way to debug variables in your browser

### ISSUE THREAD

**Issue by dwarcher** [sintaxi/harp#430]
Apologies for posting this as an issue, but here is a simple way to debug print variables for troubleshooting template issues - 

https://gist.github.com/dwarcher/8b52fa650b1c06a924fc

It would be helpful to have in your docs. I played around with a couple things for a few hours before realizing this simple solution.

**Comment by kennethormandy** [comment]
Hey, thanks. In the past we’ve also used `pre: code= JSON.stringify(public, 0, 2)` to show everything on the page. If you’re interested in adding it to the docs, would you mind opening up a pull request there?

https://github.com/harp/harpjs.com

Thanks so much!
