### ISSUE TITLE
auto-generate skeleton blog posts

### ISSUE THREAD

**Issue by gilesbowkett** [sintaxi/harp#433]
It would be nice if you could say `harp new post` and harp would automagically get some of the basic grunt work out of your way.

I've seen this feature requested in two separate places:

https://github.com/sintaxi/harp/issues/97#issuecomment-27163146
https://github.com/sintaxi/harp/issues/356#issuecomment-57527029

I wrote up a cheesy and simple implementation of it here:

https://gist.github.com/gilesbowkett/ea886e8040b50aa4896a

It's in CoffeeScript rather than JS, it's very quick and dirty code, and it includes a number of small idiosyncrasies that are relevant for my company's blog, but possibly not for anybody else's. But it gets the basic point across, and you're free to mess with it if you like.

And, if anybody wants to try to integrate this with the `harp` command-line tool, they appear to both be built upon the same npm package.

**Comment by kevinsimper** [comment]
It could be an idea just to create a module called npm-new-post and then just call that :)

**Comment by gilesbowkett** [comment]
makes sense. is there a way to plug into Harp, though? or would it have to be like `new-harp-post title "My Awesome Post"` etc? I'd prefer `harp new-post title "My Awesome Post"`, if possible.

**Comment by kevinsimper** [comment]
In what ways would you plug into harp? Your plugin would create a markdown file and update the _data.json with the title and filename.

**Comment by gilesbowkett** [comment]
well, as I said above, I'd like to be able to say `harp new-post` rather than `new-harp-post`.

that is to say, I'd prefer to plug new functionality into the existing `harp` command-line tool, rather than write a whole new one. this script is a whole new command-line tool of its own already, and that's really the only thing I don't like about it.

> Your plugin would create a markdown file and update the _data.json with the title and filename.

my script already does. :-)

it seems silly to put something so simple on npm, although I suppose I could. I'm just putting it here because I've seen people asking for this functionality in various discussions elsewhere in this repo. just want to demonstrate that it's easy to implement.

**Comment by kennethormandy** [comment]
Hey! Thanks for the suggestion and opening an issue! Since Harp is a web server, we try and avoid making decisions that benefit blogs specifically. We’re happy to tweet out or link to your npm module if you want to release it that way though, though.

Other option would be to make whatever functionality you need a run script in your `package.json` (with our without another module) and it looks like [a Grunt task](https://github.com/dwarcher/grunt-harp-post) was put together too if you really want it configured very specifically.
