### ISSUE TITLE
Parse HTML in json

### ISSUE THREAD

**Issue by siamakmokhtari** [sintaxi/harp#435]
Hi.
I have a json file like above and I want when compile page with Harp, parse HTML DOMs. How can do it?

```javascript
{
	"slug": {
		"title": "Hello-world",
		"lead": "<b>Far</b> far away, behind the <sup>word mountains</sup>, far from the countries Vokalia and Consonantia"
	}
}
```

**Comment by antipodeman** [comment]
Learn to use Google.
The first link from the search results gives the answer:
http://www.thorntech.com/2012/07/4-things-you-must-do-when-putting-html-in-json/
