### ISSUE TITLE
Can not install after node update to 0.12.2

### ISSUE THREAD

**Issue by redyyu** [sintaxi/harp#437]
# Keep showing me

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "harp"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! version not found: terraform@0.10.3
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/redy/npm-debug.log
# 

Did try re install nodejs.

ps: It's work fine before last night. but can not working now.

**Comment by cvburgess** [comment]
I can confirm I am having the same issue

**Comment by redyyu** [comment]
Couple days study, I figure it out. now the problem is fixed by change to another npm source.
btw, still have problem with harp update, I believe it's the same issue.

**Comment by sintaxi** [comment]
Sorry things have been a bit quiet. Thanks for keeping us updated.
