### ISSUE TITLE
`sudo npm...` is NOT recommended!

### ISSUE THREAD

**Issue by dmitriz** [sintaxi/harp#439]
Your main page https://github.com/sintaxi/harp advises to 

    sudo npm ...

which is neither necessary [nor recommended by the creator of `npm`](http://foohack.com/),
see also http://stackoverflow.com/a/29787667/1614973

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue. While I personally agree with you, sadly recommending `sudo` still this seems to be the most effective way to deal with this problem still. We could add a _You may need to preface this command with `sudo`_ note wherever we recommend it, which is what we do on the blog sometimes. I’ll open on an issue on the docs…
