### ISSUE TITLE
Assets versioning

### ISSUE THREAD

**Issue by Spone** [sintaxi/harp#440]
Is there a way to add versioning to static assets (css, js, images) during for the compiled output? It would help with user-side cache-related issues when deploying a new version.

Something like https://www.npmjs.com/package/gulp-rev

I think it would be useful to have this option built-in, similarly to what you did with autoprefixer.

Let me know if you want me to provide additional details.

**Comment by kevinsimper** [comment]
You can do it as a `npm run task`.

This can be a part of you after `harp compile && npm run post-buildstep`

https://github.com/kevinsimper/harp-browserify
