### ISSUE TITLE
How to implement "current url" in harpjs template?

### ISSUE THREAD

**Issue by cuekin** [sintaxi/harp#444]
in hugo.io  =
"https://www.facebook.com/sharer/sharer.php?u= {{ .Permalink }}"

in blogger.com =
"https://www.facebook.com/sharer/sharer.php?u= + data:post.url +"

how to do it in harpjs ?

i need it, not just for social sharer script, but also for other template customization
Thank You Very Much.

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue. Does this help? http://harpjs.com/docs/development/current

**Comment by kennethormandy** [comment]
Hey, if this didn’t solve your issue, feel free to re-open.
