### ISSUE TITLE
TypeError - Cannot read property 'split' of null

### ISSUE THREAD

**Issue by yunspace** [sintaxi/harp#445]
Hi, I've recently upgraded Harp version 0.17.0 and trying to generated a RSS feed and replacing the relative image links in my CDATA `/img/blah.png` with full image url: `http://blah.com/blog/img/blah.png`. 

Similar to @kennethormandy's example here:

https://github.com/harp/harpjs.com/blob/master/public/blog/newsletter.xml.jade#L18

So my code looks something like this:

    item
        title= post.title
        description 
          <![CDATA[!{ partial(slug).split("</p>")[1].replace(/src="\/img/g, 'src="http://blah.com/blog/img')   }]]>
        pubDate= new Date(post.date)
        link #{ url }/blog/#{ post }
        guid(isPermaLink="true") #{ url }/blog/#{ post }

However I get the following error `TypeError - Cannot read property 'split' of null` 
I tried taking one stage back and do:

    <![CDATA[!{ partial(slug).replace(/src="\/img/g, 'src="http://yunspace.com/blog/img') }]]>
        pubDate= new Date(post.date)

But now I get `Cannot read property 'replace' of null`. Without `split` nor `replace` my CDATA generates correctly. Is there something that has changed in the latest Jade upgrade or I'm missing something in my syntax? Thanks.

**Comment by kennethormandy** [comment]
Hey! What does your `for` loop look like? Does you have something called `slug`?

In mine, it was like this:

```
for article, slug in public.blog._data
```

…so I could call `partial()` on the `slug` later. I guess what I’m asking is, can you post the whole file?

**Comment by yunspace** [comment]
Sure thing, here it is:

    doctype xml    
    rss(version="2.0" xmlns:atom="http://www.w3.org/2005/Atom")
      channel
        title= title
        link= url
        description= description
        atom:link(href="#{ url }/blog/atom.xml", rel="self", type="application/rss+xml")
        for post, slug in public.blog._data
          item
            title= post.title
            description 
              <![CDATA[!{ partial(slug).split("</p>")[1].replace(/src="\/img/g, 'src="http://yunspace.com/blog/img') }]]>
            pubDate= new Date(post.date)
            link #{ url }/blog/#{ post }
            guid(isPermaLink="true") #{ url }/blog/#{ post }

Actually my whole repo is available here: https://github.com/yunspace/yunspace.ninja

The template I'm using based on your `hb-simurai`. However I changed the `atom.xml.ejs` into `atom.xml.jade`.

**Comment by yunspace** [comment]
I found out the issue. There were entries in my _data.json which contains empty `CDATA []` therefore the split will end with `null` values. The fix was simply to a check for:

    for post, slug in public.blog._data
      if (post.title && post.published !== false) 
        item:

Schoolboy error. Sorry for the false alarm and thanks for looking into this. Closing.
