### ISSUE TITLE
URI is missing ')' from <file>.sass

### ISSUE THREAD

**Issue by juliancoleman** [sintaxi/harp#447]
When using a URI on a SASS import (namely google fonts import URLs), it considers the // in the URL to be an expected comment line and the application and will ignore the rest of the line to the next newline character.

    @import url('http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic|Roboto:400,300,400italic,500,700,900');

**Comment by kennethormandy** [comment]
I think this is the expected behaviour actually. Since that is an `@import` to a remote CSS file, not a local Sass or SCSS file, it will just get output as plain CSS.

Mind sharing what version of Harp you are on? Then we’ll know what version of Libsass & Node-sass this is in.

**Comment by juliancoleman** [comment]
I don't believe it is expected behavior so much. Harp seems to interpret the `//` in `http://` as a single-line comment, dismissing the URL entirely, including the closing parenthesis. It should recognize it as a URL instead of asserting the `//` as a comment. If that makes sense.

I'm currently using harp 0.17.0

Thanks a bunch

**Comment by nkgm** [comment]
As a workaround see: 
https://github.com/sass/libsass/issues/143#issuecomment-30845782
