### ISSUE TITLE
Markdown Metadata Preprocessing Support?

### ISSUE THREAD

**Issue by ryanfitzer** [sintaxi/harp#45]
Docs say this is supported, but I'm not seeing the expected result.

Here's the content of test.md (using .markdown returns a 404):

``` html
# Welcome to #{ globals.name }
```

When I navigate to http://localhost:9966/test, `#{ globals.name }` is not replaced.

**Comment by insanetisane** [comment]
Hi, I'm having no luck with the partial function pointing to a markdown file. Nothing shows up. I'm trying to most basic of examples. Can someone confirm that this works?
`article!= partial("_stats-text")`
_stat-text.md file is in same directory.
