### ISSUE TITLE
Harp Server 0.17.0 doesn't render

### ISSUE THREAD

**Issue by jdsimcoe** [sintaxi/harp#452]
When I run `harp server` using Harp `0.17.0` doesn't render anything and returns this error:

![screen shot 2015-05-27 at 4 01 20 pm](https://cloud.githubusercontent.com/assets/275617/7849394/bc57cf70-0489-11e5-9020-f2e7f0f268a0.png)

**Comment by jdsimcoe** [comment]
@sintaxi @kennethormandy Any ideas on this. Harp Server appears to be running in the Terminal:

```bash
------------
Harp v0.17.0 – Chloi Inc. 2012–2015
Your server is listening at http://localhost:9000/
Press Ctl+C to stop the server
------------
```

But nothing renders in the browser. Any ideas?

**Comment by jdsimcoe** [comment]
I've also re-installed Harp and it still happens.

**Comment by kennethormandy** [comment]
You could check if you have [a port conflict](http://harpjs.com/docs/environment/port-conflicts)? Or try running Harp on a different port:

```sh
harp server -p 9001
```

**Comment by jdsimcoe** [comment]
Dang, that's probably it:

```bash
harpjs.com git/master  284s
❯ lsof -i ':9000'
COMMAND PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
php-fpm 335 jdsimcoe    6u  IPv4 0x1b1d1f066b6b5327      0t0  TCP localhost:cslistener (LISTEN)
php-fpm 487 jdsimcoe    0u  IPv4 0x1b1d1f066b6b5327      0t0  TCP localhost:cslistener (LISTEN)
php-fpm 488 jdsimcoe    0u  IPv4 0x1b1d1f066b6b5327      0t0  TCP localhost:cslistener (LISTEN)
php-fpm 489 jdsimcoe    0u  IPv4 0x1b1d1f066b6b5327      0t0  TCP localhost:cslistener (LISTEN)
```

Looks like php-fpm is running there. Don't know how to stop that. So weird. I know I can switch ports but PHP shouldn't be running there.

**Comment by jdsimcoe** [comment]
I killed them via `sudo kill -9` but that was weird. Thanks @kennethormandy!

**Comment by jdsimcoe** [comment]
So @kennethormandy is there a config where I can set the Harp port to `9001` by default when I run `harp server`?

**Comment by jdsimcoe** [comment]
@kennethormandy Nevermind... thanks for all the help man.

**Comment by timsnadden** [comment]
If there is a port conflict then harp ought to detect this and throw an error on startup.
