### ISSUE TITLE
modules is-property and balanced-match are missing

### ISSUE THREAD

**Issue by hastebrot** [sintaxi/harp#453]
In order to run `harp init _harp` I had to manually install some additional npm packages. 

Windows 7, Harp 0.17.0, io.js 2.2.1.

```
npm install -g harp
npm install -g is-property
npm install -g balanced-match
npm install -g https://github.com/sintaxi/terraform#release-v0.11.1
```

Error messages looked like this:

```
Error: Cannot find module 'is-property'
```

**Comment by kumarvishalvishnoi** [comment]
Seems fine to me.
Steps:-

1. Open cmd and move to <node_modules> folder in your project,like
C:\<>\<>\node_modules

2. Then try command
npm install -g balanced-match
