### ISSUE TITLE
BabelJS support

### ISSUE THREAD

**Issue by nicolo-ribaudo** [sintaxi/harp#455]
Hi! Can harp support the [babel](http://babeljs.io) compiler?

**Comment by glued** [comment]
I have a harp boilerplate here https://github.com/glued/harp-babel but it would be great addition to harp even gulp is using it now for gulpfiles :+1:

**Comment by kennethormandy** [comment]
Thanks for opening an issue! We have an open pull request for this we’re considering merging, feel free to weigh in on what the extension should be there. https://github.com/sintaxi/terraform/pull/82
