### ISSUE TITLE
harp not installing in ubuntu 12.04 

### ISSUE THREAD

**Issue by gopirajum** [sintaxi/harp#461]
sudo npm install -g harp
npm http GET https://registry.npmjs.org/harp

npm ERR! Error: failed to fetch from registry: harp
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/gopiraju/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "harp"
npm ERR! cwd /home/gopiraju
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: harp
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gopiraju/npm-debug.log
npm not ok

**Comment by jdcauley** [comment]
@gopirajum it looks like your npm may be out of date, I believe current version is 2.12.1

**Comment by kennethormandy** [comment]
Actually I think that version of npm would still be fine, but the version of Node is quite old. We only support Node v0.10.x and up, and you are currently running v0.6.12. You can [download the latest version here](http://nodejs.org), and everything should work fine! Fee free to re-open the issue if that doesn’t fix it. Thanks for trying out Harp!
