### ISSUE TITLE
Support for CSON

### ISSUE THREAD

**Issue by vbwx** [sintaxi/harp#463]
Since Harp already compiles CoffeeScript automatically (which is awesome), it would come in handy to build in CSON to JSON conversion (https://github.com/bevry/cson). This can have two use cases:
* `.cson` files can be served as `.json`.
* Developers can create `_harp.cson` and `_data.cson` files instead of their JSON counterparts.

**Benefits:** Less typing, comments are allowed, multiline strings

What do you think?

**Comment by kennethormandy** [comment]
Hey! We were really on board with making it possible to have an entirely whitespace-significant project at one point, but this didn’t end up getting finished. Here’s where we got to:

- [Discussion](https://github.com/sintaxi/terraform/issues/43)
- [Tests](https://github.com/kennethormandy/terraform/tree/cson)
- [Initial PR](https://github.com/sintaxi/terraform/compare/master...sorahn:cson)

I’m going to close it in favour of https://github.com/sintaxi/terraform/issues/43, not sure what the verdict is right now but I am personally fine with it.
