### ISSUE TITLE
Google Analytics recipe page has multiple issues

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/harp#466]
The GA recipe (http://harpjs.com/recipes/google-analytics) looks like someone was editing an old page and forgot to finish it. It has a lot of parts from a contact form recipe.

**Comment by jdcauley** [comment]
@sintaxi @kennethormandy are docs available somewhere to do a PR?

**Comment by kennethormandy** [comment]
Yep! https://github.com/harp/harpjs.com/blob/master/public/recipes/google-analytics.md

**Comment by cfjedimaster** [comment]
Darnit, you mean I can't just complain, I have to actually fix stuff?

On Tue, Jul 28, 2015 at 2:02 PM, Kenneth Ormandy <notifications@github.com>
wrote:

> Yep!
> https://github.com/harp/harpjs.com/blob/master/public/recipes/google-analytics.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sintaxi/harp/issues/466#issuecomment-125721935>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by kennethormandy** [comment]
Ha! Well I think you’ve exceeded your quota for helping us, @cfjedimaster, so you’re fine. ;) The docs are open source, but the recipes section in particular was unfortunately never fully realised.

**Comment by cfjedimaster** [comment]
Too late - I took a stab at it.

On Tue, Jul 28, 2015 at 2:12 PM, Kenneth Ormandy <notifications@github.com>
wrote:

> Ha! Well I think you’ve exceeded your quota for helping us, @cfjedimaster
> <https://github.com/cfjedimaster>, so you’re fine. ;) The docs are open
> source, but the recipes section in particular was unfortunately never fully
> realised.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sintaxi/harp/issues/466#issuecomment-125723835>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by kennethormandy** [comment]
Merged and live, thanks for the help! http://harpjs.com/recipes/google-analytics
