### ISSUE TITLE
Cannot make any calls to jQuery in harp despite including the library in template

### ISSUE THREAD

**Issue by iani** [sintaxi/harp#467]
Hello everyone

I have a question regarding jQuery in Harp: I cannot make a jQuery call in ejs or jade

Even though I am including jQuery min or js with the full path

I have tried both with installing jquery through bower, and with pre-configuerd examples from github

For example I tried this in my test.ejs file:

<script> $(document).ready(function(){
     $("button").click(function(){
         $("p").hide();
     }); }); 
</script>

 Or this:

<% $(document).ready(function () {
   $('.accordion-tabs').each(function(index) {
     $(this).children('li').first().children('a').addClass('is-active').next().addClass('is-open').show();
   });
   $('.accordion-tabs').on('click', 'li > a.tab-link', function(event) {
     if (!$(this).hasClass('is-active')) {
       event.preventDefault();
       var accordionTabs = $(this).closest('.accordion-tabs');
       accordionTabs.find('.is-open').removeClass('is-open').hide();

      $(this).next().toggleClass('is-open').toggle();
      accordionTabs.find('.is-active').removeClass('is-active');
      $(this).addClass('is-active');
    } else {
      event.preventDefault();
    }
  });
});    

the last one was from an example of bourbon refills

My includes are in the template files. jade:

_layout.jade
     script(src="/Users/iani/Documents/Dev/Web/harp-learning1506/19-component-neat-install-test/bower_components/jquery/dist/jquery.min.js")
     script(src="/Users/iani/Documents/Dev/Web/harp-learning1506/19-component-neat-install-test/js/jquery-1.10.2.js")

The paths are taken from emacs easy-kill and are correct as tested from terminal

Harp complains in the rendered file on localhost:3000 : ReferenceError - $ is not defined

I tried this also in an extra file in a configuration cloned from: 
commadelimited/jQuery-Mobile-Harp-Boilerplate.git

I am running with gulp like this: 

var gulp        = require('gulp');
var browserSync = require('browser-sync');
var cp          = require('child_process');
var harp        = require('harp')

gulp.task('serve', function (done) {
    harp.server(__dirname, {
        port: 9000
    });
});

gulp.task('build', function (done) {
    cp.exec('harp compile ./public dist', {stdio: 'inherit'})
        .on('close', done)
});

gulp.task('watch', function () {
    gulp.watch("public/*.{jade,ejs,styl,haml,sass,scss,less}", browserSync.reload)
});

gulp.task('browser-sync', function() {
    browserSync({
        proxy: "localhost:9000"
    });
});

gulp.task('default', ['serve', 'browser-sync', 'watch']);

Any ideas? 

jQuery examples should be included in the documentation, if possible. That would be very helpful
Thanks

Iannis Zannos

**Comment by kennethormandy** [comment]
Hey there,

EJS and Jade are for templating the reusable pieces of code you want to be compiled down to static HTML, CSS, and JavaScript (for example, iterating over blog posts). The jQuery examples you have still need to run client-side, in the browser: they dynamically switch between accordion tabs, or whatever else. So you don’t actually need to run them within your EJS templates, which is what you’re currently trying to do by putting that jQuery code within the EJS `<% %>` tags block.

Instead, just include the jQuery code in a `script` tag, so it will run in your browser. Try this instead:

```html
<script>
$(document).ready(function () {
$('.accordion-tabs').each(function(index) {
$(this).children('li').first().children('a').addClass('is-active').next().addClass('is-open').show();
});
$('.accordion-tabs').on('click', 'li > a.tab-link', function(event) {
if (!$(this).hasClass('is-active')) {
event.preventDefault();
var accordionTabs = $(this).closest('.accordion-tabs');
accordionTabs.find('.is-open').removeClass('is-open').hide();

  $(this).next().toggleClass('is-open').toggle();
  accordionTabs.find('.is-active').removeClass('is-active');
  $(this).addClass('is-active');
} else {
  event.preventDefault();
}
});
});
</script>
```

Hope that is helpful! :)
