### ISSUE TITLE
Harp Server blocking on Windows

### ISSUE THREAD

**Issue by ArrayKnight** [sintaxi/harp#469]
I'm having some issues with running any tasks after harp server. For example, here is a portion of my package.json:

"scripts": {
    "start": "harp server & gulp babel & gulp watch",
    "test": "echo \"Error: no test specified\" && exit 1"
}

Any tasks (even if run "concurrently") that come after harp server fail to ever execute. I have verified that reordering does allow tasks to run though not in the correct order. When running the harp server first, the server details show up in the console and the site is live and reachable at localhost:9000, but the console "hangs" on a blinking cursor. Hang isn't quite the right word since it still responds to Ctrl+C to shutdown the server.

Versions:
Windows 8.1
Git (Bash) 1.9.5
Harp 0.17.0 (also tested against 0.15.2)
Node 0.12.6 (also tested against 0.12.4)
NPM 2.11.2

**Comment by olegshilov** [comment]
Have same issue.
