### ISSUE TITLE
Specify browsers for autoprefixer users browserslist

### ISSUE THREAD

**Issue by rocketnova** [sintaxi/harp#472]
Since terraform has [autoprefixer](https://github.com/postcss/autoprefixer) as a dependency, I thought I would be able to add a `browserslist` [config file](https://github.com/postcss/autoprefixer#browsers) to specify the autoprefixers I wanted harp to prefix. But nothing seems to be happening. I know harp generally wants to keep the configuration to a minimum, so is there something in harp preventing my browserslist file from being used?

**Comment by igorshubovych** [comment]
+1
