### ISSUE TITLE
Sass & co. as plugins for harp?

### ISSUE THREAD

**Issue by goloroden** [sintaxi/harp#474]
Now, that io.js 3.0.0 was released, [node-sass doesn't work anymore](https://github.com/sass/node-sass/issues/1053) - once again :-(

A quite central problem here is that node-sass makes use of C++ and hence is vulnerable to changes in V8. This in turn means that harp does not run on top of io.js 3.0.0.

This made me think how this could be solved ... basically, what about turning all the precompilers to plugins for harp, so that the user can decide which ones to install and use and which ones not to install and use? Basically, similar to express?

**Comment by saper** [comment]
I'd say that io.js 3.0 is very fresh and there will be lots of rough edges to be ironed out, not only for binary modules. It is not always advisable to immediately to jump to the latest...

**Comment by goloroden** [comment]
Of course you are right there, and I surely do not want to offend anyone… so please don't be mad at me, *but*: When new versions of Node / io.js are published, it's quite often sass that's causing trouble with harp, not the other precompilers. And this is due to the fact that sass depends on C++ bindings, and is not pure JavaScript.

I don't want to be harsh, and I am definitely thankful for all the hard and great work that people like you put into sass, but it's annoying as a user of harp that you regularly can not upgrade to the new Node / io.js version, because one single precompiler (that you perhaps do not even use!) is causing problems.

Hence, I had the thought, that it *may* be a good idea to make harp more modularized, so that people can choose which precompilers to use and which not to use. That's basically all.

As said before… please don't be mad at me. I do not want to do harm to anybody :-)

**Comment by saper** [comment]
No offense taken :) It is just a consequence of riding on a wild development path. That's what io.js is all about :)
