### ISSUE TITLE
site_title and other site_ variables are returning undefined

### ISSUE THREAD

**Issue by jdsimcoe** [sintaxi/harp#477]
@sintaxi @kennethormandy I can't figure out why but all the variables in my `harp.json` are not showing up in my `.jade` files and are returning `undefined`. Here is my `harp.json`:

``` json
{
  "globals": {
    "site_title": "Circle",
    "site_description": "The Internet for Your Family",
    "site_keywords": "circle,connected family,family internet,smart family internet",
    "site_author": "Circle,Circle Media Inc.",
    "copyright": "2105. Circle Media Inc.",
    "site_url": "http://meetcircle.com"
  }
}
```

What am I missing?

**Comment by sintaxi** [comment]
I wouldn't be surprised if this has something to do with where you have your `harp.json` file. Can you me your project structure? And the commands you are using to run harp?

**Comment by jdsimcoe** [comment]
`harp.json` is in the root folder. All other files are in `public/`.

The Harp command is this to build:

`harp compile public www && browserify main.js -t babelify > www/assets/js/bundle.js`

This is my start script:

`watchify main.js -t babelify -o public/assets/js/bundle.js & harp server public`

Does `harp.json` need to be in the public/ folder?

**Comment by douggr** [comment]
I had the very same issue 2 minutes ago :) You are running in *Framework style*. From [docs](http://harpjs.com/docs/development/rules):
> When a project contains a harp.json file and an explicit public/ directory, the public/ directory will be served instead of the root. In Framework Style, Public assets belong in the public/ directory. Assets outside of the public directory will not be served.

Try this:
```sh
# to build
harp compile && browserify main.js -t babelify > www/assets/js/bundle.js

# Local server
watchify main.js -t babelify -o public/assets/js/bundle.js & harp server
```

**Comment by jdsimcoe** [comment]
Thanks @douggr

**Comment by FaridSafi** [comment]
I fixed this by creating the `_harp.json` inside the `/public` folder
