### ISSUE TITLE
.cson support where ever .json is applicable

### ISSUE THREAD

**Issue by SusanthCom** [sintaxi/harp#480]
Feature request :
    **.cson** support where ever .json is applicable for configuration files

It will be nice and more complete to write configurations in .cson;  making it more user-friendly,  especially for **CoffeeScript** users.

Atom.io is making use of .cson extensively. 
.cson >> https://github.com/bevry/cson

Thank you

**Comment by kennethormandy** [comment]
We have a PR for this, but haven’t had a chance to evaluate it yet. https://github.com/sintaxi/terraform/pull/102 We’re fairly open to it though, the idea being you should be able to have an entirely whitespace-significant stack within Harp if you want.

I’m going to close this issue, but if you want, feel free to post comments there.

**Comment by SusanthCom** [comment]
Thanks @kennethormandy  and @vbwx for the efforts. 
waiting to see it going live :)
