### ISSUE TITLE
harp server refreshes _harp.json but not _data.json — requires restart

### ISSUE THREAD

**Issue by lunelson** [sintaxi/harp#483]
So, I'm on Harp 0.17.0, and can not get any changes/additions to `_data.json` files to show up in jade templates, unless I restart the server. AFAIK, the various _data files should be walked and rebuilt on every request, if [this comment](https://github.com/sintaxi/harp/issues/335#issuecomment-54388814) is correct.

Stopping and restarting the server works for now; but is obviously not ideal. Am I just doing something wrong or is this how it is?

**Comment by lunelson** [comment]
Seems to be fixed on the 0.18.0 release :smile:

**Comment by tjfwalker** [comment]
Running 0.19.0 and this issue is present.
Reopen.

**Comment by kennethormandy** [comment]
Hey @tjfwalker, thanks for commenting. Is the project you’re experiencing this with on GitHub, so we can try it out? This is not something we’ve ever been able to re-produce, but we’ll definitely take it seriously if we can figure out what is happening. Also, mind sharing what version of Node and what OS you’re using? THanks!
