### ISSUE TITLE
compile time route mapping

### ISSUE THREAD

**Issue by SusanthCom** [sintaxi/harp#486]
Hi @sintaxi  @kennethormandy 

```
// Proposed Feature Request
```
### Thoughts

Wiki engines like moinmoin encourages **flat** URL structure rather than having deeply nested URL structure. The motto is to use hierarchy URL only when really necessary; most of time unique flat URL is preferred.

Using harp this is possible; but to have large number of files at root level makes a big list of mess. 

Another suggested way is to keep related files organised in different folders and do compile time route mapping in `harp.json` or  `data.json`. This give more flexibility in organising files and more control over published URLs.
### harp.json or _data.json

``` javascript
{
  "__routemap": "/documents:/doc" // String syntax; acting on folder
  "__routemap": ["/business:/", "/personal:/"] // Array syntax; acting on folder
  "__routemap": "/some-folder/real-name.md:/published-name.html" // String syntax; acting on file
}
```
### Real File Structure

```
/business/
   | bz-todo.md
   | xyz-company.md
   | staff-list.md
/personal/
   | me.md
   | my-todo.md
   | home-info.md
   | hobby.md
```
### Published URL after Compilation

http://example.com/bz-todo.html
http://example.com/xyz-company.html
http://example.com/staff-list.html
http://example.com/me.html
http://example.com/my-todo.html
http://example.com/home-info.html
http://example.com/hobby.html
### Non Existing URL after Compilation

http://example.com/business/bz-todo.html
http://example.com/business/xyz-company.html
http://example.com/business/staff-list.html
http://example.com/personal/me.html
http://example.com/personal/my-todo.html
http://example.com/personal/home-info.html
http://example.com/personal/hobby.html

Thank you

**Comment by davej** [comment]
Might be nice to use the same JSON formatting as Divshot's Superstatic and keep it compatible rather than creating a new JSON format for this. https://github.com/divshot/superstatic#configuration

**Comment by SusanthCom** [comment]
@davej  nice :) Super static  has good runtime options. 
The suggestion mentioned is about Compile time publishing option.
As you said, its nice to follow well know / proven way of config file syntax. :+1:
