### ISSUE TITLE
Add more documentation of lib usage

### ISSUE THREAD

**Issue by lunelson** [sintaxi/harp#491]
The "lib" usage of harp seems to be pretty sparsely documented. In the main `README` it is mentioned that you can set up a Harp application like this

``` js
var harp = require("harp")
harp.server(projectPath [,args] [,callback])
```

... but no further information seems to exist about the `args` or the `callback`. Am I just looking in the wrong place?

**Comment by kennethormandy** [comment]
Here’s the docs page: http://harpjs.com/docs/environment/lib
We also have a PR which discusses some of the newer features:  https://github.com/harp/harpjs.com/pull/56 I’ll get that merged soon

Let us know if that’s helpful. It’s possible the README just needs a review

**Comment by lunelson** [comment]
Thanks for those links; but both are mainly about using Harp as middleware with Express. It's mentioned only in passing, that there's a `harp.server()` method but in my testing it doesn't seem to work on its own: is it possible to fire up Harp from a script, without using Express? I basically just want the equivalent of the CLI command `harp server` but that I can run from inside of a larger script
