### ISSUE TITLE
Inconsistent file order?

### ISSUE THREAD

**Issue by fedosejev** [sintaxi/harp#492]
I see two different orders when the same files are served and compiled.

My `_data.json` file:

``` json
{
  "thoughts": [
    "biznes-sekrety-2-0-mihail-fridman",
    "tesla-model-x"
  ]
}
```

When I serve and print `public.thoughts._data.thoughts;` on a webpage, the order is:
`biznes-sekrety-2-0-mihail-fridman,tesla-model-x`

Then when I compile, the order changes to:
`tesla-model-x,biznes-sekrety-2-0-mihail-fridman`

Any advise on why this is happening is much appreciated.

**Comment by EdgeCaseBerg** [comment]
+1 

I was about to ask a similar question but it might be related, to reproduce:
```
mkdir test && cd test;
harp init
```
Create index.jade:
```
h1 Welcome to Harp.
h3 This is yours to own. Enjoy.
for post, slug in public._data
  a(href="/#{slug}")
    h2= post.title
```
with _data.json:
```
{
    "test" : {
        "title" : "Test"
    },
    "test-2" : {
        "title" : "test-2"
    },
    "126" : {
        "title" : "126"
    }
}
```

will show 126 first rather than the other two.
