### ISSUE TITLE
HTML minifying does not work (is it supposed to?)

### ISSUE THREAD

**Issue by welblaud** [sintaxi/harp#493]
Whatever I have tried, I can’t made harp to minify the html output. Development as well as production mode, compilation of the project, nothing helps. Every CSS is neatly minified but the html source is a real whitespace mess. I have tried to reduce it with .replace() on the yield, commenting the gap between tags (<something></something>), no way.

harp 0.17.0, ubuntu 14.04

**Comment by kennethormandy** [comment]
We process HTML, CSS, or JavaScript right now, but if you are using Jade or EJS (or even just rename your `.html` file to `.ejs`) the contents should be minified.

Let us know how that goes! Also, you might like to update to the latest version of Harp, [v0.19.0](http://harpjs.com/blog/v0-19-0-npm-3-compatibility).

**Comment by welblaud** [comment]
Thanks for the information. Actually, I use .ejs there. Is that functionality associated with an environment?

**Comment by kennethormandy** [comment]
Yes, all HTML compiled from Jade or EJS templates should be minified. Do you happen to have the project on GitHub so we can take a look?

**Comment by welblaud** [comment]
I don’t at the moment. Would it be sufficient?
```javascript
<% var articles = public.articles._data; %>
<% function excerpt(content) {
  if (content.indexOf("<!-- more -->") == -1) return content.replace(/<h3>(.*?)<\/h3>/g, "");
  else return content.split("<!-- more -->")[0].replace(/<h3>(.*?)<\/h3>/g, "");
} %>
<% function body(content) {
  return content.replace(/<h3>(.*?)<\/h3>/g, "");
} %>

<ul>
  <% for (var slug in articles) { %>
    <% if (articles[slug].published !== false) { %>
      <li class="posts">
      <a class="post-link" href="/articles/<%= slug %>"><%= articles[slug].title %></a>
      <span class="date">(<%= articles[slug].date %>)</span><br/>
      <%- excerpt(partial("articles/" + slug)) %>
      <div class="read-more">
        <a class="read-more-link" href="/articles/<%= slug %>">read more</a><br/>
      </div>
      <div class="categories">
        <% var categories = articles[slug].categories %>
          <% if (categories !== undefined) { %>
            <% for (var i = 0; i < categories.length; i++) { %>
              <% if (categories[i] !== "vim tips") { %>
                <span class="category"><a class="category-link" href="<%= categories[i] %>"><%= categories[i] %></a></span>
              <% } else { %>
                <span class="category"><a class="category-link" href="/vim"> vim tips</a></span>
              <% } %>
            <% } %>
          <% } %>
        </div>
      </li>
    <% } %>
  <% } %>
</ul>
```

**Comment by welblaud** [comment]
It seems it is really associated with ejs, not Harp itself. My code supports empty linefeeds. If I reduce some closings and put them before linefeeds and if I reduce the overall amount of ejs comments, it works! This could be closed. Thanks for the attention.
