### ISSUE TITLE
disable compression for JS and CSS (server mode)

### ISSUE THREAD

**Issue by og2t** [sintaxi/harp#494]
I use CoffeeScript and indented SASS in my projects and everything works as a charm :) Despite debuging – JS and CSS are now being compressed into one line, which makes it impossible to debug.

Is there any way to disable that? I guess it's a new feature, as it wasn't there in 0.14 and below?
It seems to make sense to minify with `harp compile`, perhaps `harp watch` could be another command for non compressed output?

Cheers!

**Comment by kennethormandy** [comment]
Harp v0.19.0 is the latest version, we’ve been minifying all preprocessed templates, CSS, and JS for a while. :) Source Maps are the way to handle this, and while we don’t support them right now, we happily would if someone wanted to submit a PR. I’m going to close this issue in favour of that: https://github.com/sintaxi/harp/issues/74 Feel free to comment there if you’d like.
