### ISSUE TITLE
Allow hostname option for multihost mode.

### ISSUE THREAD

**Issue by farias-r7** [sintaxi/harp#501]
I'm trying to add the ability to specify a hostname to use when launching the node server in multihost mode. I've removed all hard coded references to "harp.nu" but for some reason harp.nu:9000 always resolves and connects to the node server. Is there anywhere other than the harp repo that this is defined? Maybe in a dependency? All my console statements print to console so I know it's running the code.

I do understand that most people serve compiled assets and use something like nginx in a production install, but we just want to be able to run harp in multihost mode on a server.

We have a main harp site that iframes parts of other harp sites. We do this because we are building a styleguide that has nested pages within the existing page. It was the easiest approach because each page has it's own set of dependencies. We also aren't using web components so it was the best approach we could think of.

**Comment by mosster** [comment]
+1, did you ever find a workaround @farias-r7 ? I ran into a similar problem https://github.com/sintaxi/harp/issues/596

**Comment by frank-dspeed** [comment]
hmmm Maybe my fork helps you a bit @farias-r7 @mosster 

https://github.com/steal-server/server 

if you run multihost it should act like harp but it uses domain folders so 

/bla.com/index.jade
/style.org/index.jade
