### ISSUE TITLE
Want to retrieve app path and options from server object in API

### ISSUE THREAD

**Issue by alexgleason** [sintaxi/harp#506]
I want to be able to do something like this:

```javascript
var harp = require("harp");
var server = harp.server(appPath, options);
console.log(server.appPath);
console.log(server.options);
```

**Comment by alexgleason** [comment]
@sintaxi This is the one I was talking about in the Hangouts chat. Without this I'm forced to save the values in global vars.

**Comment by alexgleason** [comment]
```javascript
var server
harp.server(appPath, {
    ip: '0.0.0.0',
    port: port
  }, function() {
    server = this
    server.appPath = appPath
    enableDestroy(server)
  })
```

I figured out I can do something like this, then access the port and IP with `server.address().port` and `server.address().address` respectively.

But as you can see I'm still needing to set `server.appPath` manually since that's not exposed as part of the object.

Also, I noticed I couldn't access the data at all if I do `var server = harp.server(...)`. I have to set `server = this` inside of the callback. I haven't dug into why exactly that is. Preferably `harp.server()` would just return an object with all the relevant data.

**Comment by sintaxi** [comment]
ok. this now works...
```
harp.server(projectPath, {
    ip: '0.0.0.0',
    port: 9001
  }, function() {
    this.projectPath
  })
```
