### ISSUE TITLE
Harp GUI

### ISSUE THREAD

**Issue by alexgleason** [sintaxi/harp#507]
Hey there. My comrade @Tetoq and I created a GUI program to start a Harp server for local development.

You can find the source code here: https://github.com/alexgleason/harp-gui/
Along with a sample video: https://www.youtube.com/watch?v=EsCQwyWNXS8

The idea came from programs like [Hammer for Mac](http://hammerformac.com/) and [Koala.app](http://koala-app.com/) which we've relied on in the past to coordinate with web designers who didn't know how to use the command line, or disliked it. Hammer is proprietary, $20, and OSX only. Koala is free/open, but it's not continually updated and is lacking in features. When I saw Harp I became excited because it can really simplify front-end development, and we decided to create a GUI application for local development in Harp.

So now I'm wondering how to move forward. We did this because we wanted to create a free and open source, cross-platform alternative to the projects I mentioned above, and don't have a desire to profit from it or anything like that. We also don't want to step on your toes, knowing that Harp is a trademark of yours. If you're interested in joining forces we would love that, or if you could give us feedback on how you'd prefer we incorporate aspects of Harp, such as the way we name our app, or any additional information that should be in the readme, etc. Pull requests welcome.

We haven't released any downloads yet, but I think the app is ready for an initial release.

Thanks!

**Comment by JayHoltslander** [comment]
Looks nice, does it have live reload capability?

**Comment by sintaxi** [comment]
Wow! this is so cool. Wonderful animations and great use of the Harp visual identity. Happy to work together to make this the best it can be. 

Im floored. This is terrific. :heart_eyes:

**Comment by alexgleason** [comment]
That's great to hear! We'd love to work together. The design and awesome animations were created by the talented @Tetoq.

Feel free to open any issues or pull requests. I'm going to try to package this up for a beta as soon as I get the vector icon from Teto. See [here](https://drive.google.com/folderview?id=0BwfNEizpnybJVGQ4T1UxMlIwQUU&usp=sharing) for Teto's mockups we worked off of. He's going to experiment with different icons in the dock to see what we think looks nice and we'll share our thoughts.

Have you ever used Electron before? It's actually super fun because you can make desktop apps really fast with Node. I want to say Teto and I spent a total of 3 days on this from the initial idea to getting it to this state. The only thing that sucks is the manual effort it takes to get it on all 3 platforms. Mac and Linux are fairly easy, but Windows requires you to sign your exe and that whole process is confusing. Then you have to test on all 3 platforms.

But yeah, anyway, I'd say start by trying out the app, submit some bugs if you see any, and maybe check out the [Electron docs](https://github.com/atom/electron/tree/master/docs/api). I added you as a collaborator so feel free to contribute code. I'll post some beta downloads as soon as I have them, but we may need help figuring out how to make the Windows installer work right.

**Comment by isaacrg** [comment]
@alexgleason While I'm no windows expert, I can try and help out with some testing and fixing of the installer.

**Comment by alexgleason** [comment]
@isaacrg Sweet, thanks! I added you as a collaborator.

**Comment by silentrob** [comment]
This is really well done indeed. I wonder if it could be paired with surge.sh for something that is end-to-end?

**Comment by alexgleason** [comment]
@silentrob Oh, cool. At a glance I don't see exactly how surge.sh works, but it looks like it's a node package, so as long as you can include it as a module and control it programatically you can build a UI for it in Electron.

**Comment by kennethormandy** [comment]
Hey @alexgleason and @tetoq, finally got some time to try this out today. Really impressive work! I ran the harpjs.com site with no trouble at all.

We wanted to talk to you about what next steps might look like. We’re definitely interested in joining forces, or figuring out an arrangement that everyone is happy with. Would you be available for a call with us sometime next week, so we can say hello and chat about things? Maybe Monday or Wednesday?

**Comment by alexgleason** [comment]
Okay! I'll talk with Teto and get back with you. At this point I think a 1.0.0 release candidate can be made and tested, it's just a matter of actually doing it. I've been busy because I'm soon moving to Philadelphia to work for a new employer, but I've had this project on my mind.

But yeah, I'll get back with you shortly!

**Comment by alexgleason** [comment]
Okay so Monday is cool with us. You're 2 hours behind us though. Can we do 12:00pm CST (10:00am PST)? Don't want to pull Teto away during working hours.

If you can do Hangouts that would be cool. Otherwise a call is fine. Send me an email to the address in my Github profile and I'll send you my info.

Thanks!

**Comment by alexgleason** [comment]
Here's a release candidate for 1.0. https://drive.google.com/folderview?id=0BwfNEizpnybJVTVGOHZ3eDR1Y2M&usp=sharing

64-bit Mac and Linux only.

Works perfectly in Linux, need someone to test for OSX. Although given the way Electron works, it should theoretically work without error. My only concern is whether the app icon shows up.

Windows is more complicated. Want to make sure these other two work fine before I touch that.

**Comment by alexgleason** [comment]
I also want to mention that Yeoman has a super cool Electron app in the works. https://github.com/yeoman/yeoman-app

How cool would it be to have the Yeoman app scaffold a Harp project then use Harp GUI to run it?

**Comment by Tetoq** [comment]
Hi Alex,
I see the icon, it looks great but in OSX doesn't work. I can open the app but nothing happens when I drag the folder and even if I click.

**Comment by alexgleason** [comment]
Hmm... very strange. May need some help to debug that one.

If you enter `/Applications/harp.app/Contents/Resources/app/` that's where the source code is. In there I tried running `electron .` on my Linux machine and it does work. So I know the files are okay, it's maybe just something operating system specific.

If you open main.js and delete/comment line 25 (`mainWindow.setMenu(null);`) you should be able to bring up the inspector with `Cmd + Opt + I` when you run it again. Maybe there's an error in the JS console after you drop the app.

**Comment by Tetoq** [comment]
Ok, this is the error:
Uncaught Error: The `libsass` binding was not found in /Applications/harp.app/Contents/Resources/app/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

**Comment by alexgleason** [comment]
lmao... of course that's the error. The error that has plagued our existence.

**Comment by alexgleason** [comment]
@Tetoq Can you make harp-gui launch on your machine from going into the git repo and running `electron .`? If so, email me this file:

./harp-gui/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-46/binding.node

It needs to be built on each platform and I overlooked that. So the version you have contains the Linux binary but not the OSX one.

**Comment by Tetoq** [comment]
Done

**Comment by alexgleason** [comment]
I updated the harp-osx.zip file in the above Google Drive folder with the osx file. Please confirm it's working. Thanks!

Does anyone know if node has to be installed for it to work, though? This worries me. Want to test on a fresh OS install and make sure it still runs even without Node.

**Comment by Tetoq** [comment]
In OSX v10.11 it seems that works perfectly.

**Comment by alexgleason** [comment]
Sweet! :+1:

**Comment by kennethormandy** [comment]
Haven’t had a chance to review all the updates yet, but this might also be related to https://github.com/sintaxi/harp/issues/510#issuecomment-154570463 depending on the version of Node you’re building things with. We’ll be updating Libsass again in the next release

**Comment by alexgleason** [comment]
http://electron.atom.io/

The official electron site also maintains a list of apps created with it. It would be cool to get this on that site.

**Comment by glued** [comment]
On a related note I just released an [atom package](https://github.com/glued/harpy) with harp integration:

![output](https://cloud.githubusercontent.com/assets/1124158/14068895/72743dec-f445-11e5-9102-aca7b8d8078d.gif)

Atom will manage node child process harp instances so you can have one for every project open in atom, auto assign a port, and open the browser. These instances will auto kill when atom closes or can be done manually. Supports OSX and Windows. I plan on adding surge support as well.

**Comment by alexgleason** [comment]
Nice work!! I'd been wanting to have that as well. :smile:

**Comment by JayHoltslander** [comment]
Dude that's awesome. Nice work.
ᐧ

On Mon, Mar 28, 2016 at 10:33 AM, Alex Gleason <notifications@github.com>
wrote:

> Nice work!! I'd been wanting to have that as well. [image: :smile:]
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sintaxi/harp/issues/507#issuecomment-202499636>
>



-- 
Jay

**Comment by sintaxi** [comment]
This is really cool. I might have to start using atom :)
