### ISSUE TITLE
Any plans for an ES6 transpiler?

### ISSUE THREAD

**Issue by DawnPaladin** [sintaxi/harp#508]
Hi there! As a newbie web developer, I'm really impressed by how much easier Harp makes my development process without adding a lot of complexity. Thank you for creating this!

I'm doing my best to learn JavaScript the Right Way™; getting the hang of ECMAScript 5 and 6 seem to be part of that. Are there any plans to include an ES6 transpiler in Harp?

**Comment by isaacrg** [comment]
Yes, there are. Specifically the babel transpiler is going to be added soon hopefully. The processing engine that powers harp is where the information on the progress of that is. See: https://github.com/sintaxi/terraform/pull/82

**Comment by DawnPaladin** [comment]
Awesome. Looking forward to the release. Thank you!

**Comment by og2t** [comment]
+1!
