### ISSUE TITLE
Add Access-Control-Allow-Origin header to harp server (CORS)

### ISSUE THREAD

**Issue by Prinzhorn** [sintaxi/harp#512]
I couldn't find any existing discussion about this, maybe I'm doing something exotic. Locally I have my node app on localhost:3000 and harp on localhost:9000 for serving static files (which is done via S3/CloudFront in production, with precompiled SASS etc.). The sad thing is that fonts/fontawesome won't work correctly:

> Font from origin 'http://localhost:9000' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Is adding an option to enable CORS for `harp server` something you would consider doing?

**Comment by sintaxi** [comment]
Yep. Im down with this. We'll try to get this into one of the next releases.

**Comment by Prinzhorn** [comment]
Will PR

**Comment by Prinzhorn** [comment]
Closing in favor on #514
