### ISSUE TITLE
Harp + for loops + Sub items

### ISSUE THREAD

**Issue by pauljakobwhite** [sintaxi/harp#513]
Hi all, this may be more of a general question, or perhaps just a jade question and not related to Harp, but I'm having trouble accomplishing the following:

I have my _data.json file set-up as such for navigation:

```json
{
  "item" : {
    "title": "Example",
      "subitems" : {
        "subitem1": {
          "title": "example-subitem"
         },
         "subitem2": {
           "title":"example-subitem2"
         }
       }
     },
     "next-item": {
       "etc. etc. etc."
     }
}   
```

I'm trying to loop over this in jade to create a navigation with sub-navigation:
e.g., 

```jade
for item in public._data
  ul
    li #{item.title}
    ul
      // another for loop of subitems inside the looped item
        li #{subitem.title}
```

Anyone know how I can accomplish this with harp/jade? or know a better method?

Thanks all!

**Comment by omichelsen** [comment]
How about:

```js
for item in public._data
  ul
    li #{item.title}
    ul
      for subitem in item.subitemList
        li #{subitem.title}
```

**Comment by kennethormandy** [comment]
Thanks @omichelsen! That looks good to me. We also added [Lodash to Harp templates in v0.20.x](http://harpjs.com/blog/v0-20-0-node-5-compatibility) if that helps what you’re trying to do at all.

**Comment by pauljakobwhite** [comment]
So I got this to work as prescribed but now I'm running into the same issue nesting even deeper...

So this is working: 

```jade
- for item, key in public._data.navigation
  li #{item.title}
    ul 
      - for subitem in item.subitems
        li #{subitem.title}
```

But I would like to take it one even two nested items deeper, i.e.:

```jade 
- for item, key in public._data.navigation
  li #{item.title}
    ul 
      - for subitem in item.subitems
        li #{subitem.title}
          ul
            - for subsubitem in subitem.subitems
              li #{subsubitem.title}
```

and likewise should that "subsubitem" contain any subitems (please excuse the excessive usage of the word sub lol)

Essentially the json looks like this: 

```json
{
     "item" : {
          "title": "Example",
          "subitems" : {
               "subitem1": {
                    "title": "example-subitem",
                    "subitems" : {
                         "etc. etc. etc..." : {...}
                    }
                }
          }
     }
}
```

Any help would be extremely appreciate, we are using an older version of harp at the moment and can not upgrade to the newer version with lodash :-/

Thank you!
