### ISSUE TITLE
Render CSS first and make available to the templates

### ISSUE THREAD

**Issue by sidonaldson** [sintaxi/harp#515]
*Possible feature request*

I'm trying to improve my sites pagespeed score by inlining priority CSS styles inside the head. It's simple to do with jade:

```
doctype
html
    ...
    style
      include css/priority.css
```

Except that during compile there is no file yet and a `ENOENT` error is returned. Also the harp server compiles on the fly so would be even harder. Is there something I can already utilise to get the compiled css?

**Comment by kennethormandy** [comment]
This has been a bug for a while: #105 (that issue description isn’t very good, sorry).

You are right this should work, but it doesn’t right now. We need this ourselves for generating email templates with Harp, so it’s definitely something we want to fix.

**Comment by sidonaldson** [comment]
That's cool, happy to close as dup!
