### ISSUE TITLE
Make Compatible to Nodejs v5

### ISSUE THREAD

**Issue by frank-dspeed** [sintaxi/harp#516]
latest nodejs version is v5

**Comment by kennethormandy** [comment]
Hey, are you running the latest version of Harp? If you install v0.20.x, [Harp is now compatible with Node v5](http://harpjs.com/blog/v0-20-0-node-5-compatibility).

Run the following command to update:

```sh
npm install -g harp
# You may need to preface this with sudo
```

Let me know if that works for you! I am going to close this issue, but feel free to open it if you are still having troubles.

**Comment by frank-dspeed** [comment]
your right it only dont worked because v5 was wrong installed
