### ISSUE TITLE
Harp + Jade nested loops from _data.json

### ISSUE THREAD

**Issue by pauljakobwhite** [sintaxi/harp#524]
Hello, 

I had posted a similar issue that is now closed but I'm hoping for some extra help here:

I'm trying to generate a nav menu from json data in the _data.json file. The json contains top level menu items with submenu items and submenu items for some of those submenu items,

So far I have this working to grab the top level and its submenu items: 

``` jade
- for item, key in public._data.navigation
  li #{item.title}
    ul 
      - for subitem in item.subitems
        li #{subitem.title}
```

But I would like to take it one even two nested items deeper, i.e.:

``` jade
- for item, key in public._data.navigation
  li #{item.title}
    ul 
      - for subitem in item.subitems
        li #{subitem.title}
          ul
            - for supersubitem in subitem.supersubitems
              li #{supersubitem.title}
```

and likewise should that "supersubitem" contain any subitems (please excuse the excessive usage of the word subitems lol)

Essentially the json looks like this: 

``` json
{
     "item" : {
          "title": "Example",
          "subitems" : {
               "somthing": {
                    "title": "example-subitem",
                    "supersubitems" : {
                         "somethingelse" :  {
                              "title" : "etc. etc. etc...",
                              "supersupersubitems" : { }
                         }
                    }
                }
          }
     }
}
```

Any help would be extremely appreciated, we are using an older version of harp at the moment and can not upgrade to the newer version with lodash :-/

Thank you!

**Comment by sarahlim** [comment]
Easy enough to implement using recursive [Jade mixin blocks](http://jade-lang.com/reference/mixins/).

Assuming the following JSON:

```json
{
  "home": {
    "title": "Home"
  },
  "about": {
    "title": "About",
    "sub": {
      "about-me": {
        "title": "About Me"
      },
      "about-dog": {
        "title": "About My Dog",
        "sub": {
          "dog-facts": {
            "title": "Facts About My Dog"
          },
          "dog-pics": {
            "title": "Pictures of My Dog"
          }
        }
      },
      "about-cat": {
        "title": "About My Cat"
      }
    }
  },
  "contact": {
    "title": "Contact Me"
  }
}
```

This Jade:

```jade
mixin menu(tree)
  ul
    for node in tree
      li= node.title
      if node.sub
        +menu(node.sub)

+menu(public._data)
```

Produces the following HTML:

```html
<ul>
  <li>Home</li>
  <li>About</li>
  <ul>
    <li>About Me</li>
    <li>About My Dog</li>
    <ul>
      <li>Facts About My Dog</li>
      <li>Pictures of My Dog</li>
    </ul>
    <li>About My Cat</li>
  </ul>
  <li>Contact Me</li>
</ul>
```
The key is to design your JSON like a tree, with a standard node interface, so that your mixin can traverse properly. Instead of naming things `supersubitem` and `supersupersubitem` etc., just use `sub` (or something else consistent) for every node.

**Comment by kennethormandy** [comment]
@sarahlim Thank you so much for taking the time to answer this! Would you be interested in opening an issue or Pull Request [on Harp’s docs](https://github.com/harp/harpjs.com), so we could share it with other peopel in the future?

It could be a multi-step nav recipe, or go as a more complicated example in the metadata section maybe. Either way, thanks!

**Comment by sarahlim** [comment]
@kennethormandy Sure thing, I'll write something up tomorrow and create a PR.

**Comment by rmccawl** [comment]
This is very useful indeed, having tried to create something similar recently, I found both Harp and Jade docs lacking. This is great.
