### ISSUE TITLE
Multiple JS / CSS Files unification

### ISSUE THREAD

**Issue by DiegoRBaquero** [sintaxi/harp#527]
Are the are plans to enable multiple files into one?

like having all js/*.js go into app.js?

Or is there a current way to do it?

I have a broccoli app that I would love to migrate to Harp.

Thank you

**Comment by eltuctuc** [comment]
+1

**Comment by matteo-bombelli** [comment]
for **css** i use less, just rename css files int less but you have to take care about **calc()** http://stackoverflow.com/questions/17904088/disable-less-css-overwriting-calc

then you can create a main.less that imports all the others
(lesscss.org/features/#import-options)

for **js** there is a workaroud for now: 
you can use ejs and use partials but they will not compile to js (https://github.com/sintaxi/harp/issues/410) so you have to call them like `app.jsscript.ejs`. linking them correctly will work as expected but is not beautyful
