### ISSUE TITLE
Mode / flag for compiling to S3-friendly directory structure?

### ISSUE THREAD

**Issue by andrewboni** [sintaxi/harp#532]
Is there a way to have Harp compile to an AWS S3 friendly structure? What I'm looking to do:
1. Have "clean" urls (e.g. `mysite.com/company/about`, instead of `mysite.com/company/about.html`)
2. Have a simple sources directory structure

To achieve this, as far as I can tell, S3 needs the site to be in a structure like this:

```
www
├── 404.html
├── company
│   └── about
│       └── index.html
├── features
│   ├── ecommerce
│       └── index.html
├── index.html
├── privacy-policy
│   └── index.html
├── resources
│   ├── case-studies
│   │   └── index.html
│   ├── partners
│   │   └── index.html
│   └── whitepapers
│       └── index.html
```

Note the number of folders & `index.html` files. Thing is, I'd like to have my sources look something like this:

```
  -www
    - 404.jade
    - index.jade
    - privacy-policy.jade
    - resources
      - case-studies.jade
      - partners.jade
      - whitepapers.jade
...
```

Right now, to achieve the desired S3 result, I have to structure the sources like this, which is pretty bloated & confusing (too many `_data.json` & `index.jade` files) and far from ideal:

```
...
├── company
│   └── about
│       ├── _data.json
│       └── index.jade
├── features
│   ├── _features.jade
│   ├── ecommerce
│   │   ├── _data.json
│   │   └── index.jade
├── index.jade
├── privacy-policy
│   └── index.jade
├── resources
│   ├── case-studies
│   │   ├── _data.json
│   │   └── index.jade
│   ├── partners
│   │   ├── _data.json
│   │   └── index.jade
│   └── whitepapers
│       ├── _data.json
│       └── index.jade
├── robots.txt
└── terms-of-service
    └── index.jade
```

Does something like this exist? Thanks!

**Comment by frank-dspeed** [comment]
Nope that don't exist and is not planned maybe you should consider coding your own dev server and compiler as this can be done in less then 30 minuts
