### ISSUE TITLE
Is there a way to add classes in Harp-Markdown?

### ISSUE THREAD

**Issue by wsw70** [sintaxi/harp#534]
An `.md` file compiles to a standard HTML with, for instance, 

    # hello

compiling  to 

    <h1>/hello</h1>

Is there a way to enrich the Markdown entry to add a class, so that the output is

    <h1 class="mine">/hello</h1>

Thank you for any pointers

**Comment by matteo-bombelli** [comment]
"<h1 class="mine">/hello</h1>" is the answer... you can put html directly in markdown

bye!

**Comment by wsw70** [comment]
@matteo-bombelli I know that I can mix up Markdown with HTML.

 I also, however, want to keep a consistent style in my document (eg. not having sometimes `# title` and sometimes `<h1>title</h1>`) and was therefore looking for native mechanisms (Markdown or Harp)  which would decorate an element with a class (I found in some dialects things like `# title {+:class: mine}`)

**Comment by matteo-bombelli** [comment]
as soon as I know markdown was not meant to do things like that... 

> Markdown is not a replacement for HTML, or even close to it. Its syntax is very small,   corresponding only to a very small subset of HTML tags. The idea is not to create a syntax that makes it easier to insert HTML tags. In my opinion, HTML tags are already easy to insert. The idea for Markdown is to make it easy to read, write, and edit prose. HTML is a publishing format; Markdown is a writing format. Thus, Markdown’s formatting syntax only addresses issues that can be conveyed in plain text.
  
>  For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.
  
>  The only restrictions are that block-level HTML elements — e.g. `<div>, <table>, <pre>, <p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

(https://daringfireball.net/projects/markdown/syntax)

jade can be the answer you're looking for...

```jade
h1.mine hello
```

**Comment by wsw70** [comment]
@matteo-bombelli Thanks. Jade would be almost an ideal solution - the only drawback is that it is not that suitable to create documents (as opposed to templates) - as you need to `br` each new line (the document then difficult to read)

**Comment by matteo-bombelli** [comment]
@wsw70 u're welcome! :smile: 

for me the ideal is try to divide **written contents** [ "pure text" ] from the **structure** directly from the planning... you can use variables in the `_data.json` file and then use them in a jade or ejs template.

if you have time, for me the best behavior is to create a `_text` folder inside `public` or [root] folder and then reference the md file inside of `_text` in the `_data.json` file. In the page.jade / page.ejs you can create a template and use the md files inside of your structure... i think of md files like "ck-editor" fields...

for me harp is very powerful and starts from basis. to use it at (what i think is) its best you have to build on it what you want to achieve

have fun coding!
