### ISSUE TITLE
Markdown not fully processed in a div

### ISSUE THREAD

**Issue by wsw70** [sintaxi/harp#535]
The following code (Windows 10, harp v. 0.20.1)

```
# title

some text before the `div`

<div markdown=1>
Some *markdown* text, with [a link](http://google.com)

- and some
- bullet points

</div>

- and some more
- bullet points in normal text
```

renders as 

![chrome_2016-01-30_14-48-36](https://cloud.githubusercontent.com/assets/1345886/12696069/9f990602-c760-11e5-9b59-b83fc9b07e32.png)

**The bullet points within the `div` are not rendered correctly.**

**Comment by roytruelove** [comment]
Can I ask what the `<div markdown=1>` markup is for?

**Comment by wsw70** [comment]
@roytruelove the contents of the `div` are supposed to be rendered as HTML and the `markdown=1`informs that Markdown elements should be processed as Markdown (and not simple text.

The thing which surprises me is that it works partially: some of the Markdown is processed correctly while some other is not.
