### ISSUE TITLE
ejs variables strange behaviour...

### ISSUE THREAD

**Issue by matteo-bombelli** [sintaxi/harp#536]
in ejs using

``` javascript
    var bar = [1,2,3,4];
    var foo = bar;
    
    foo[0]=5;
```

inside a `<% %>` tag will result in:

``` javascript
bar = [5,2,3,4];
```

is that the right behaviour?

using `const` doesn't change the results (`bar = [5,2,3,4];`)...

**Comment by matteo-bombelli** [comment]
Sorry I was wrong: 
I checked and this is the default behavior of nodejs.
To solve that use JSON stringify and JSON parse.

**Comment by sintaxi** [comment]
Thanks for the update!
