### ISSUE TITLE
Range error when compiling

### ISSUE THREAD

**Issue by jaukia** [sintaxi/harp#538]
When calling "harp compile . ../build" I keep getting range error, even when I remove all files from the directory that is compiled! It looks like the compile works and the static files are generated correctly.

Harp server works ok.

Running Os X 10.11.2, Node.js version v4.3.1, NPM version 2.14.12, Harp version 0.20.1.

Error starts like this:

```
Transformers.verbatim is deprecated, to continue using the :verbatim jade filter after jade@2.0.0, you will need to install jstransformer-verbatim.
/usr/local/lib/node_modules/harp/lib/index.js:0

RangeError: Maximum call stack size exceeded
  at String.replace (native)
  at Object.exports.shouldIgnore (/usr/local/lib/node_modules/harp/node_modules/terraform/lib/helpers/raw.js:423:23)
  at copyFile (/usr/local/lib/node_modules/harp/lib/index.js:232:27)
  at replenish (/usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:176:21)
  at /usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:188:33
  at copyFile (/usr/local/lib/node_modules/harp/lib/index.js:238:7)
  at replenish (/usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:176:21)
  at /usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:188:33
  at copyFile (/usr/local/lib/node_modules/harp/lib/index.js:238:7)
  at replenish (/usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:176:21)
  at /usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:188:33
  at copyFile (/usr/local/lib/node_modules/harp/lib/index.js:238:7)
  at replenish (/usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:176:21)
  at /usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:188:33
  at copyFile (/usr/local/lib/node_modules/harp/lib/index.js:238:7)
  at replenish (/usr/local/lib/node_modules/harp/node_modules/async/lib/async.js:176:21)
```

**Comment by lunelson** [comment]
I'm getting this too, as of this morning

**Comment by bauhouse** [comment]
I'm running into the same issue on `harp compile`: `RangeError: Maximum call stack size exceeded`

Except that for me, compile is modifying some of the binary assets (images and videos) when there are no changes to these files.

Running OS X 10.11.3, Node version 5.1.0, NPM version 3.5.3, Harp version 0.20.1

**Comment by naomiblack** [comment]
I'm seeing the same issue. OS X 10.11.3, Node 4.1.1, NPM 2.14.7, Harp 0.20.1.

I can temporarily fix by deleting and recreating my github client, but that seems unnecessarily extreme...

**Comment by sintaxi** [comment]
Thanks for reporting this. Does anyone happen to have a reliable way to reproduce this issue?

**Comment by jvandemo** [comment]
@sintaxi &mdash; Cloning https://github.com/angular/angular.io and running:

```bash
$ npm install
$ npm run harp -- compile . ./www
```

consistently reproduces the problem.

I have troubleshooted a bit and replacing `async.eachLimit` with `async.each` on https://github.com/sintaxi/harp/blob/master/lib/index.js#L252 and https://github.com/sintaxi/harp/blob/master/lib/index.js#L256 seems to fix the problem.

Not sure if `eachLimit` is required or recommended over `each`. If not I can provide a quick PR to fix the problem.

Feel free to let me know how to proceed. Thanks!

**Comment by jvandemo** [comment]
Quick update: the fix above seems to work well for the Angular team as well: https://github.com/angular/angular.io/issues/982

**Comment by bauhouse** [comment]
Thank you! Just to confirm, this fix in Harp version 0.20.3 has resolved the RangeError issue for me as well.

**Comment by sintaxi** [comment]
Great. Thanks for reporting.

**Comment by naomiblack** [comment]
I've just had this crop up again on Angular, using 0.20.3...

We do have a large number of small files in our site, due to examples for our developer docs.

```
RangeError: Maximum call stack size exceeded
  at String.replace (native)
  at Object.exports.shouldIgnore (/Users/naomib/.nvm/versions/node/v4.1.1/lib/node_modules/harp/node_modules/terraform/lib/helpers/raw.js:423:23)
  at copyFile (/Users/naomib/.nvm/versions/node/v4.1.1/lib/node_modules/harp/lib/index.js:232:27)
  at replenish (/Users/naomib/.nvm/versions/node/v4.1.1/lib/node_modules/harp/node_modules/async/lib/async.js:176:21)
  at /Users/naomib/.nvm/versions/node/v4.1.1/lib/node_modules/harp/node_modules/async/lib/async.js:188:33
```

**Comment by jvandemo** [comment]
@naomiblack &mdash; When I:

- clone https://github.com/angular/angular.io
- run `npm install`
- run  `gulp _harp-compile`

it seems to output the `www` directory correctly. I can also run `gulp serve-and-sync` without issues.

Which exact commands are you running? (I will try to reproduce locally)

Thanks!

**Comment by matthewmayer** [comment]
Note, I'm pretty sure that this is due to the fact that copyFile sometimes calls its callback synchronously. See https://github.com/caolan/async#synchronous-iteration-functions for a solution using `setImmediate`.

**Comment by jvandemo** [comment]
@naomiblack &mdash; I have created a gist with a change to harp to handle the file copies and compilations asynchronously, as @matthewmayer suggested.

You can find the gist here:
https://gist.github.com/jvandemo/caeaef6cc3073cd19760d6b841642524

I haven't been able to reproduce the problem here locally, so can you try and replace `node_modules/harp/lib/index.js` in your local `angular.io` repository with the contents of the gist and see if that resolves your problem?

If it does, I can create a PR to the harp repository. Thanks!

**Comment by sintaxi** [comment]
I'm really bogged down right now. How do you feel about having commit rights an you run with it?

**Comment by jvandemo** [comment]
@sintaxi &mdash; Whatever you feel most comfortable with Brock. It would be an honor to help you out with this.

**Comment by jvandemo** [comment]
Quick update: received feedback from @naomiblack that she wasn't able to reproduce the issue consistently and that there was another issue that was causing too many files to be created.

So all is ok for now until further notice.

**Comment by sintaxi** [comment]
Thanks for the update. Happy to hear this isnt a problem.
