### ISSUE TITLE
Add support for YUICompressor

### ISSUE THREAD

**Issue by L8D** [sintaxi/harp#54]
For example, if you point to a `*-min.js` or `*.min.js` and the is no matching file, then harp should use YUICompressor on the equivalent non-minified file. There should also be a command line option for disabling/enabling the compression feature for the `harp compile` command.

**Comment by jeremyhaile** [comment]
Some of my vendor files I include unminified in the project during development, but want to use them compressed in production. I wish that there was a way to have them be automatically minified, either in production mode or when `harp compile` is run.
