### ISSUE TITLE
Unable to add Excerpt using Jade

### ISSUE THREAD

**Issue by amandeepmittal** [sintaxi/harp#541]
//- excerpt
- function excerpt(content) 
   return content.split("")[0];
-}

shows syntax error for '-' (hyphen) and if I remove hyphen shows syntax error for '}' end curly brace.

**Comment by chharvey** [comment]
did you mean this?

    //- excerpt
    - function excerpt(content) return content.split("")[0]; -}

If so, I see 2 syntax errors:
1. no opening curly brace before the word `return`
2. hyphen precedes closing curly brace

**Comment by amandeepmittal** [comment]
I certainly did. However, it does not looks as confusing as your emoji sounds. 
Also, the issue was solved by myself months back so I am closing it now. The curly brace was missing before return.
