### ISSUE TITLE
upgrade jade version to support block code

### ISSUE THREAD

**Issue by chharvey** [sintaxi/harp#543]
I'm not exactly sure which version of Jade this package is dependent on, since it is not listed under the package.json's `dependencies` or `devDependencies`. If that were more clear, I would have simply submitted a pull request.

Anyhow, when I run a static server (with `$ harp server`) and attempt to view my Jade file in the browser, **it does not compile** because of the unbuffered block code.

```
-
  var data = {
    heading: 'hello'
  }
h1= data.heading
```

However, it does compile when single-line unbuffered code is used.

```
- var data = { heading: 'hello' }
h1= data.heading
```

The [block code syntax](http://jade-lang.com/reference/code/) is supported in [Jade v1.11.0](http://jade-lang.com/history/). Please upgrade Harp to the latest version of Jade.

**Comment by lunelson** [comment]
This will be fixed as soon as https://github.com/sintaxi/harp/pull/526 is merged

**Comment by chharvey** [comment]
also, keep in mind:
https://github.com/pugjs/pug/issues/2184

**Comment by chharvey** [comment]
also see https://github.com/sintaxi/terraform/issues/114

**Comment by sintaxi** [comment]
I believe this issue is now resolved.
