### ISSUE TITLE
Error while starting server

### ISSUE THREAD

**Issue by pkorzeniewski** [sintaxi/harp#549]
When starting a server with the `harp server` command, I get a following error:

```
\harp\bin\harp:88
var host = this.address()
                       ^
TypeError: this.address is not a function
```

Harp version: 0.20.2
Node version: 4.4.2 (also tested on 5.10.0)
NPM version: 2.15.0
OS: Windows 7 x64

**Comment by joshpangell** [comment]
I am getting the same error.

Harp version: 0.20.2
Node version: 4.4.2
NPM version: 3.8.5
OS: El Capitan (10.11.4)

**Comment by sintaxi** [comment]
Thanks for reporting so quickly I think some commits snuck into master which should not be there. Will get a hot fix out asap.

**Comment by sintaxi** [comment]
Just released `harp@0.20.3`. Do you mind verifying this resolves to problem for you?

**Comment by joshpangell** [comment]
Worked like charm.

Thanks!

**Comment by pkorzeniewski** [comment]
Workes fine :)

**Comment by sintaxi** [comment]
Thanks for testing!
