### ISSUE TITLE
Issue with compilation

### ISSUE THREAD

**Issue by santoshsankar** [sintaxi/harp#550]
Hi,

I ran harp compile locally and copied the files to my remote server on Digital Ocean. It is available here -- [santoshsankar.com](http://www.santoshsankar.com). How do I fix the links so they don't break?

Thanks,
Santosh

**Comment by sintaxi** [comment]
You appear to be using NGINX to serve your application which doesn't support clean urls by default. To fix this you can do one of the following...

1. server with Harp instead of NGINX (be sure to use `NODE_ENV=production` flag)
2. configure NGINX to support clean URLs
3. don't use clean URLs
