### ISSUE TITLE
Harp Serve works and renders code as expected, Harp Compile fails every time. 

### ISSUE THREAD

**Issue by iammatthias** [sintaxi/harp#552]
Pretty much just the title. I can run Harp Serve and see what I'm working on in the browser, no problem. Everything renders as expected. But when I run Harp Compile, I get an error. It is always some variation of this:

> {
>   "source": "Sass",
>   "dest": "CSS",
>   "filename": "/Users/iammatthias/Sites/harp/canvas/node_modules/bulma/bulma/base/content.sass",
>   "lineno": 19,
>   "name": "Sass Error",
>   "message": "Undefined variable: \"$text-strong\".",
>   "stack": ".content\n  @extend .block\n  // Inline\n  li + li\n    margin-top: 0.25em\n  // Block\n  blockquote,\n  p,\n  ol,\n  ul\n    &:not(:last-child)\n      margin-bottom: 1em\n  h1,\n  h2,\n  h3,\n  h4,\n  h5,\n  h6\n    color: $text-strong\n    font-weight: 300\n    line-height: 1.125\n    margin-bottom: 20px\n  h1,\n  h2,\n  h3\n    &:not(:first-child)\n      margin-top: 40px\n  blockquote\n    background: $background\n    border-left: 5px solid $border\n    padding: 1.5em\n  h1\n    font-size: 2em\n  h2\n    font-size: 1.75em\n  h3\n    font-size: 1.5em\n  h4\n    font-size: 1.25em\n  h5\n    font-size: 1.125em\n  h6\n    font-size: 1em\n  ol\n    list-style: decimal outside\n    margin-left: 2em\n    margin-right: 2em\n    margin-top: 1em\n  ul\n    list-style: disc outside\n    margin-left: 2em\n    margin-right: 2em\n    margin-top: 1em\n    ul\n      list-style-type: circle\n      margin-top: 0.5em\n      ul\n        list-style-type: square\n  // Sizes\n  &.is-medium\n    font-size: $size-5\n    code\n      font-size: $size-6\n  &.is-large\n    font-size: $size-4\n    code\n      font-size: $size-5\n"
> }
> [1]    17826 segmentation fault  harp compile

It changes sometimes, and fails at a different line.

**Comment by iammatthias** [comment]
Tried to reinstall Harp, still getting the same issue. 

> {
>   "source": "Sass",
>   "dest": "CSS",
>   "filename": "/Users/iammatthias/Sites/harp/canvas/node_modules/bulma/bulma/base/generic.sass",
>   "lineno": 2,
>   "name": "Sass Error",
>   "message": "Undefined variable: \"$body-background\".",
>   "stack": "@charset \"utf-8\"\n\n@import \"generic\"\n@import \"content\"\n@import \"highlight\"\n@import \"helpers\"\n"
> }
> [1]    19880 segmentation fault  harp compile

**Comment by iammatthias** [comment]
I have a very kludge-y workaround for now. I run _harp server_, and then clone down localhost:9000 with wget. 

_harp compile_ still is not working.

**Comment by sintaxi** [comment]
what does your directory structure look like? do you have a /public dir?

**Comment by iammatthias** [comment]
I don't have a folder specifically called /public. My directory structure is based off of what _harp init_ provides. 

This is what I have in my project folder: 

> ├── 404.ejs
> ├── _content
> │   └── _base.ejs
> ├── _layout.ejs
> ├── _shared
> │   ├── _footer.ejs
> │   └── _header.ejs
> ├── css
> │   ├── _stickyfooter.sass
> │   ├── _style.sass
> │   └── main.sass
> ├── humans.txt
> ├── img
> ├── index.ejs
> ├── js
> ├── node_modules
> │   ├── colors.css
> │   ├── links.css
> │   ├── milligram
> │   ├── normalize.css
> │   └── type.css
> │   
> └── robots.txt

**Comment by iammatthias** [comment]
I'm curious if it's something with the Bulma CSS framework, since the SASS compiling is what chokes each time. I just swapped it out for Milligram, and will report back in a bit.

**Comment by sintaxi** [comment]
Try this. Change your directory structure to the following. and put all your web assets into the public directory...
```
project
  |- README.md
  |- package.json
  |- harp.json
  |- node_modules/
  `- public/
```

**Comment by iammatthias** [comment]
Still got the error with the new directory structure using the Bulma CSS framework. Switched to Milligram, and _harp compile_ is now working with both directory structures. 

Thanks for the help!

**Comment by tijhaart** [comment]
FYI: I got a segmentation fault as well and was most likely, caused by logging (using `@warn`). Once I removed all logging `harp compile` worked again.
