### ISSUE TITLE
Assets loading only on reload

### ISSUE THREAD

**Issue by nifl** [sintaxi/harp#553]
When I load a page served by `harp serve` the CSS and JS doesn't load unless the page is reloaded. This behavior alternates with each load so on the third reload the assets will again be absent but on the fourth all is well until the next page load. 

On the initial page load, there is no `class` attribute associated with body. The next load adds class to body and the next one removes it again. I've removed all scripts from my site and this behavior persists.

**Comment by sintaxi** [comment]
This still an issue? Any chance you can provide steps to reproduce the issue?
