### ISSUE TITLE
Jade is called Pug now

### ISSUE THREAD

**Issue by jeremytribby** [sintaxi/harp#554]
See pugjs/pug#2184

Is Harp waiting for the Pug 2.0.0 release or ... ? That release could be some time off, but if projects like Harp that are already using Jade start transitioning now I bet it would help that timeline.

**Comment by sintaxi** [comment]
Harp will most likely stick with Jade.

**Comment by jeremytribby** [comment]
> Harp will most likely stick with Jade

@sintaxi Because Jade is feature complete as-is or because no one likes the name Pug? 😛 I really wish they'd fought to keep it.

**Comment by sintaxi** [comment]
At this point in time Harp is best served sticking with ".jade" regardless of which implementation it uses. There are countless blog posts, books, video casts, documentation, tutorials, and presentations on Jade. Changing this is making up work and will be of no benefit to anyone.

**Comment by jeremytribby** [comment]
> Changing this is making up work and will be of no benefit to anyone.

Agreed, though I do sympathize with the legal position Jade's core team is in. Maybe a community that is unwilling to change will prompt the other Jade to reconsider, or prompt a fork where the only functional difference is `s/pug/jade/` :)

**Comment by sintaxi** [comment]
As far as I'm aware the maintainers have signed a gag order which means they may not be able to take part in this conversation. A significant amount of mindshare and documentation exists around jade so it makes sense to me to continue to call it jade. I think it would be cool to see pug become its own thing. I'm going to close this issue.
