### ISSUE TITLE
node-sass stops install

### ISSUE THREAD

**Issue by dcsan** [sintaxi/harp#556]
have a new DO droplet and installed nvm
node 5.9.1

installer failed as follows

```
npm install -g harp
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/root/.nvm/v5.9.1/bin/harp -> /root/.nvm/v5.9.1/lib/node_modules/harp/bin/harp

> node-sass@3.4.2 install /root/.nvm/v5.9.1/lib/node_modules/harp/node_modules/node-sass
> node scripts/install.js

sh: 1: node: Permission denied
/root/.nvm/v5.9.1/lib
└── (empty)

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/root/.nvm/v5.9.1/bin/node" "/root/.nvm/v5.9.1/bin/npm" "install" "-g" "harp"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/www/rikai.co/npm-debug.log
npm ERR! code 1

$ harp
No command 'harp' found, did you mean:

```

**Comment by swartzrock** [comment]
Seeing the same error trying to install on OS X El Capitan with the latest NPM from Homebrew:

> npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install" "-g" "harp"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.

**Comment by grsabreu** [comment]
The same here

```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR                      [49/2853]
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/gabriel/.node-gyp/6.1.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/gabriel/.nvm/versions/node/v6.1.0/lib/node_modules/harp/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/gabriel/.node-gyp/6.1.0/inc
lude/node -I/home/gabriel/.node-gyp/6.1.0/src -I/home/gabriel/.node-gyp/6.1.0/deps/uv/include -I/home/gabriel/.node-gyp/6.1.0/deps/v8/include -I../..
/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -MMD -MF 
./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:0:
../src/sass_context_wrapper.h:8:26: fatal error: sass/context.h: No such file or directory
compilation terminated.
binding.target.mk:103: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/gabriel/.nvm/versions/node/v6.1.0/lib/node_modules/harp/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gabriel/.nvm/versions/node/v6.1.0/lib/node_modules/harp/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/home/gabriel/.nvm/versions/node/v6.1.0/bin/node" "/home/gabriel/.nvm/versions/node/v6.1.0/lib/node_modules/harp/node_modules/node-
gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/gabriel/.nvm/versions/node/v6.1.0/lib/node_modules/harp/node_modules/node-sass
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
/home/gabriel/.nvm/versions/node/v6.1.0/lib
└── (empty)
```

**Comment by grsabreu** [comment]
As I tested here, it worked just great in node 5.4.1 and npm 3.8.6

**Comment by timkinnane** [comment]
+1. node v6.1.0, npm v3.8.9. Guess I'll downgrade npm for now, as per @grsabreu's comment.

**Comment by timkinnane** [comment]
Tried with both npm v3.8.7 and v3.8.6 and got the same error. Also tried with and without node-sass pre-installed. Finally got it going again by going back to node 5 (v5.11.1) and npm v3.8.6.

**Comment by xzyfer** [comment]
There are multiple issue here, all of which have been covered many times on the node-sass tracker.

@dcsan npm scripts won't run lifecycle scripts as root. You need to add the `--unsafe-perm`

```
npm install --unsafe-perm
```

@swartzrock @grsabreu node-sass added Node 6 support in v3.7.0. The version you're using, v3.4.2, is very old and no long supported. Use that latest node-sass and you'll be fine.

**Comment by xzyfer** [comment]
I have PR terraform, which harp uses, to update node-sass - https://github.com/sintaxi/terraform/pull/130

**Comment by kozie** [comment]
So, the fix has been merged into the master branch of Terraform but no new releases of both Terraform and HarpJS have been published yet.
Will there be a release to fix the Node 6.x issues or do we have to wait for a bigger update with the new changes?

no hard feelings.. i do like what you are doing and love HarpJS but i'm regretting i still haven't downgraded my NodeJS. I simply didn't do that because i didn't expect the fix to take this long. 

Thanks in advance

**Comment by sintaxi** [comment]
Ok I tagged and released Terraform v1.1.0 but Im getting failing tests when its merged into harp. Can any one take a look for me? I have things in branch https://github.com/sintaxi/harp/tree/v0.21.0-pre

**Comment by kozie** [comment]
Ok, thanks for the quick actions. I'll try and take a look asap.

**Comment by xzyfer** [comment]
@sintaxi is there a travis ci build I can see the failure on?

**Comment by jvandemo** [comment]
@sintaxi &mdash; I have v0.21.0-pre running locally and tests (`npm test`) run fine:

```
90 passing (9s)
```
What errors are you seeing?

I don't see any Travis integration so I'm assuming you run tests locally.

Thanks!

**Comment by xzyfer** [comment]
It looks like a lot has change between terraform v0.13.2 and v1.1.0. The node-sass change may be unrelated to the failures you're seeing.

**Comment by MortalCatalyst** [comment]
its node-sass 467 that has been open years causing this, current unable to install, is there a way to use sass from rubygems to get around the node-sass issues https://github.com/sass/node-sass/issues/467

**Comment by MortalCatalyst** [comment]
I can get a compile if I use 4.4.5 only at the moment

**Comment by negritosuave** [comment]
Having this same issue. npm v3.9.3 and node v6.2.1 with zsh. Recently updated node but everything was fine before. I could install and update packages so I figured it must be Harp. Came looking and found this. I was really looking forward to trying/using Harp. Hoping for a fix soon.

**Comment by stonecauldron** [comment]
Have the same problem on npm v3.9.3 and node v6.2.1 on a fresh os installation.

In my case the error seems to come from the fact that the release of node-sass is not found on github:
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/linux-x64-48_binding.node":

HTTP error 404 Not Found
```
The url used does not point to any release in the node-sass git repo.

**Comment by xzyfer** [comment]
You need at least node-sass@3.7.0 for Node 6 support.

**Comment by negritosuave** [comment]
Yes I read that before. I updated node-sass before I tried to install Harp. Still the same issue.

**Comment by DTrejo** [comment]
I just ran tests for the branch you pushed, v0.21.0-pre.
@jvandemo you can see some errors:
- https://gist.github.com/DTrejo/965ce5c714f498cde446e696276ba79d#file-output-txt-L596-L597 
- the two highlighted lines were red in my output. not to mention the abort trap stuff at the end of the output.

It's true, I am running an old OSX, so maybe you should ignore me.

**Comment by negritosuave** [comment]
I really want to try harp and I use homebrew (as well as zsh). So I looked up a different version with brew and downgraded to node 5. Harp installed and everything appears to be working. Guess I'll stick with node 5 until whatever is going on has been resolved. 

Glad that it works at least. I may downgrade to LTS just to be safe but that's down the line. Good luck!

**Comment by arxpoetica** [comment]
Bump. This really needs to be fixed.

**Comment by dcsan** [comment]
someone on our team made a hackaround script to overwrite terraform. fragile but it seemed to work

> Oh, and one more thing - you can probably use terraform Git repo directly without saving it locally (but this will slow down later reinstalls and can possibly break in the future)

```
#!/bin/sh
sudo npm uninstall --global harp
mkdir ~/fixes
cd ~/fixes
git clone git@github.com:sintaxi/harp.git
git clone git@github.com:sintaxi/terraform.git
cd terraform
npm install
cd ../harp
npm uninstall --save terraform
npm install --save ~/fixes/terraform
cd ..
sudo npm install --global ~/fixes/harp
```

**Comment by gringolalia** [comment]
I downgraded to node version 4.0.0 with `nvm` and `nvm use` and then harp installed just fine, and my `harp init harpo` command initiated the project. 

Just that now `harp server harpo` throws an error ... address in use, probably just need to reboot ...

**Comment by Heliosophist** [comment]
Installing using node v7.0.0 and npm v4.0.0 fails when compiling node-sass.I followed dcsan's procedure and it works great.I also replaced node-sass verrsion to the latest in terraform's package.json and no problems so far

**Comment by dcsan** [comment]
I was looking for an SSG for another project and then had all the flashbacks of fighting of this issue... is there any resolution in sight? otherwise unfortunately cannot really use harpjs.

**Comment by CrisLi** [comment]
Is there any way to disable sass feature since we only need the markdown feature?

I mean not install node-sass dependence and start up harp server without sass support.

**Comment by dcsan** [comment]
I guess one option might be to have a docker image for harp you could run as a container... seems a shame that a simple SSG is "rendered" haha unusable a CSS lib 😱 . I've always had problems with sass since meteor days. why do people pick it over stylus?

**Comment by DTrejo** [comment]
###### Another idea: make a version of terraform which only loads compilers/sass/etc for the languages that harp sees in the filesystem (meaning if you don't use sass, it won't load sass). 

- Problem: if you add a new file, it needs to `require` the compiler for it
- Problem: not a good idea to `require` while running

###### Idea: Maybe moving to a js version of sass will solve all these problems https://github.com/medialize/sass.js 
- Problem: slower; meant to be used in browser.

**Comment by sintaxi** [comment]
@DTrejo totally Im on board with switching to that lib or just not shipping with sass built in. Do you happen to know how mature sass.js is?

**Comment by DTrejo** [comment]
I don't know, but here are some screenshots which may help you make a decision:

![image](https://cloud.githubusercontent.com/assets/56119/24454423/aee510aa-1440-11e7-970c-2e8b04107a17.png)

![image](https://cloud.githubusercontent.com/assets/56119/24454446/bce5d0e0-1440-11e7-93e3-d4ef45bd7b37.png)

![image](https://cloud.githubusercontent.com/assets/56119/24454459/c51fd06c-1440-11e7-880a-913efe30a4b1.png)
electron-compilers: 60 releases, 20 dependants; qwebs 141 releases, 10 dependants

![image](https://cloud.githubusercontent.com/assets/56119/24454592/3e9673ce-1441-11e7-9c9b-458e5c2eb752.png)

![image](https://cloud.githubusercontent.com/assets/56119/24454605/522f97da-1441-11e7-9bb4-2f5e44fc62f7.png)

![image](https://cloud.githubusercontent.com/assets/56119/24454624/672af8be-1441-11e7-83c7-42a4a00307ff.png)

![image](https://cloud.githubusercontent.com/assets/56119/24454641/759e25ba-1441-11e7-9217-4e4b1717ecdb.png)

Hmm... seems pretty well used

**Comment by arxpoetica** [comment]
@paulirish has one commit, so... 😆

**Comment by nmors** [comment]
facing the same issue as OP on ubuntu 16.10, node 7.7.4 via nvm, latest node-sass still gets the permission denied problem. The same build works fine on Windows build agent, just not Linux

**Comment by dylan-baskind** [comment]
Would love to see this resolved - its brought our marketing site deployment to a grinding halt :( - and we're not using SASS anyhow.

**Comment by DTrejo** [comment]
Dylan, maybe you should buy some consulting from sintaxi and he'll take
care of this PR ;)

**Comment by strpipe** [comment]
Oh this is a shame. I ran into this right now. Hope this will be resolved :3

**Comment by AdamBrodzinski** [comment]
Still broke. @dcsan 's fix worked like a charm though! 🍻 

Node - v9.6.1
npm - v5.6.0

**Comment by bryantnate** [comment]
Tried the solution by @dcsan , but I couldn't clone the github repos...
```
root@bryantnate:~/fixes# git clone git@github.com:sintaxi/harp.git
Cloning into 'harp'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
root@bryantnate:~/fixes# git clone git@github.com:sintaxi/terraform.git
Cloning into 'terraform'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by sintaxi** [comment]
Fixed.
