### ISSUE TITLE
Support for Swig?

### ISSUE THREAD

**Issue by eromoe** [sintaxi/harp#562]
After searching around , I found `harp` , it is really easy to create static site, great work!
And I have to say, I am a python develop and like to use syntax as Django/Jinja template engine.

Below answer also show the pros of Swig:
http://stackoverflow.com/questions/16513168/what-are-the-pros-and-cons-of-both-jade-and-ejs-for-node-js-templating

**Comment by RobErskine** [comment]
I'd also love support for Swig. I'll take a look and see how hard it is to drop in.
