### ISSUE TITLE
Doesn't work with Node 6.x

### ISSUE THREAD

**Issue by JeffreyATW** [sintaxi/harp#564]
I'm having issues similar to #510 - but instead of Node 5, I can't install Harp on Node 6.

It looks like Harp loads Terraform 0.13.2, which loads node-sass 3.4.2, which has no bindings for Node 6.x.

Is there work on updating Harp to use a newer version of Terraform?

**Comment by theolampert** [comment]
@JeffreyATW a workaround for the moment is to use the pre-release 0.21 version of harp, point your package.json to the  github repo: `"harp": "https://github.com/sintaxi/harp.git#v0.21.0-pre"` this will load the latest version of terraform.

**Comment by kozie** [comment]
You can also install harp globally with:

```
npm i -g sintaxi/harp#v0.21.0-pre
```

Omit the `-g` and add `--save-dev` to add it to your package.json. Don't forget to `sudo` if you want to install harp globally and are on a *nix environment ;)

**Comment by mkchandler** [comment]
Are there any estimates on when v0.21 will be released?

**Comment by kozie** [comment]
I'm starting to wondering also.. feels like a dead project :(

**Comment by sintaxi** [comment]
a pre-release for v0.21 went out last week. If you are looking for ways to help we need the pre-releases to get used and bugs reported. Sorry for the poor communication.

https://github.com/sintaxi/harp/issues/571#issuecomment-245817249

**Comment by sintaxi** [comment]
Just cut `harp@0.21.0-pre.1` with a fix for this. Please use it by running `npm install -g harp@next` and report any issues you find.

**Comment by mkchandler** [comment]
Thanks @sintaxi for the update! I have been running the original pre-release without any issues for a while, but will upgrade to the official pre-release and report back any issues. Thanks for all the time and effort you put in to making harp!

**Comment by mkchandler** [comment]
@sintaxi So far everything is working as expected with `harp@next`

**Comment by jorrit** [comment]
Same here, thanks!
