### ISSUE TITLE
"yield" is a bad name for the content variable

### ISSUE THREAD

**Issue by stuartpb** [sintaxi/harp#569]
Harp should use a name other than "yield" for [the content of a page](https://harpjs.com/docs/development/yield), seeing as how `yield` [is an ES6 keyword for generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield).

Why not call it `content`? That's what pretty much every Jade layout I've ever seen calls it (usually as the name of a block).

**Comment by silentrob** [comment]
I remember fondly having this conversation in the Mozilla office back in
2013. We knew this day would come.

**Comment by sintaxi** [comment]
Haha. "ES6 is never going to land". :)

**Comment by stuartpb** [comment]
Yeah, and before io.js, that probably would have been my answer, too, but in 2016, it's a totally different story.

**Comment by bherila** [comment]
So why don't we rename it?
