### ISSUE TITLE
not installed harp to windows 10 , have many errors 

### ISSUE THREAD

**Issue by kselax** [sintaxi/harp#573]
Hello! 
Tried installed and and couldn't . 
got this errors
**C:\WINDOWS\system32>npm install -g harp
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\Neo\AppData\Roaming\npm\harp -> C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\bin\harp

> node-sass@3.4.2 install C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-ia32-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

```
  export HTTP_PROXY=http://example.com:1234
```

or configure npm proxy via

```
  npm config set proxy http://example.com:8080
```

> spawn-sync@1.0.15 postinstall C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\spawn-sync
> node postinstall
> 
> node-sass@3.4.2 postinstall C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\Program Files\nodejs\node.exe',
gyp verb cli   'C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\bin\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.3.1 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb check python launcher python executable found: "C:\Python27\python.exe"
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.12\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.3.1
gyp verb command install [ '6.3.1' ]
gyp verb install input version string "6.3.1"
gyp verb install installing version: 6.3.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.3.1
gyp verb build dir attempting to create "build" dir: C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Neo\.node-gyp\6.3.1\include\node\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\Neo\.node-gyp\6.3.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\Neo.node-gyp\6.3.1
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for ia32 C:\Users\Neo.node-gyp\6.3.1\Release\node.lib
gyp info spawn C:\Program Files\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 8/16/2016 5:31:02 PM.
Project "C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\binding.sln" on node
1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Win32".
The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files\MSBuild\Mic
rosoft\NuGet\Microsoft.NuGet.targets (186,61)" does not exist in the project, and will be ignored.
Project "C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\binding.sln" (1) is b
uilding "C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\binding.vcxproj" (2)
on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\binding\".
  Creating directory "Release\obj\binding\binding.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\binding\binding.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /I"C:\Users\Neo.node-gyp\6.3.1\include\node"
   /I"C:\Users\Neo.node-gyp\6.3.1\src" /I"C:\Users\Neo.node-gyp\6.3.1\deps\uv\include" /I"C:\Users\Neo.node
  -gyp\6.3.1\deps\v8\include" /I....\nan /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAM
  E=binding /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_
  DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D BUILDING_NODE_EXTENSION /D _WINDLL /GF /Gm- /
  MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\binding\" /Fd"Release\obj\b
  inding\vc140.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /analyze- /errorReport:queue /MP ..\src\binding.cp
  p ..\src\create_string.cpp ..\src\custom_function_bridge.cpp ..\src\custom_importer_bridge.cpp ..\src\sass_c
  ontext_wrapper.cpp ..\src\sass_types\boolean.cpp ..\src\sass_types\color.cpp ..\src\sass_types\error.cpp ..\
  src\sass_types\factory.cpp ..\src\sass_types\list.cpp ..\src\sass_types\map.cpp ..\src\sass_types\null.cpp .
  .\src\sass_types\number.cpp ..\src\sass_types\string.cpp "C:\Users\Neo\AppData\Roaming\npm\node_modules\harp
  \node_modules\node-gyp\src\win_delay_load_hook.cc"
  binding.cpp
  create_string.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_context_wrapper.h(8): fatal
 error C1083: Не удается открыть файл включение: sass/context.h: No such file or directory (компилируется исхо
дный файл ..\src\binding.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build
\binding.vcxproj]
  custom_function_bridge.cpp
  custom_importer_bridge.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\custom_function_bridge.h(5): fat
al error C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исх
одный файл ..\src\custom_function_bridge.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules
\node-sass\build\binding.vcxproj]
  sass_context_wrapper.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\custom_importer_bridge.h(5): fat
al error C1083: Не удается открыть файл включение: sass/functions.h: No such file or directory (компилируется
исходный файл ..\src\custom_importer_bridge.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modu
les\node-sass\build\binding.vcxproj]
  boolean.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_context_wrapper.h(8): fatal
 error C1083: Не удается открыть файл включение: sass/context.h: No such file or directory (компилируется исхо
дный файл ..\src\sass_context_wrapper.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\no
de-sass\build\binding.vcxproj]
  color.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\boolean.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
\build\binding.vcxproj]
  error.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\color.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\b
uild\binding.vcxproj]
  factory.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\error.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\b
uild\binding.vcxproj]
  list.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\factory.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\factory.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sa
ss\build\binding.vcxproj]
  map.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\list.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\bu
ild\binding.vcxproj]
  null.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\map.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\bui
ld\binding.vcxproj]
  number.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\null.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\bu
ild\binding.vcxproj]
  string.cpp
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\number.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\
build\binding.vcxproj]
  win_delay_load_hook.cc
c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal err
or C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходный
файл ..\src\sass_types\string.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\
build\binding.vcxproj]
Done Building Project "C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\binding
.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\binding
.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\binding.sln" (default target)
 (1) ->
"C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\build\binding.vcxproj" (default tar
get) (2) ->
(ClCompile target) ->
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_context_wrapper.h(8): fat
al error C1083: Не удается открыть файл включение: sass/context.h: No such file or directory (компилируется ис
ходный файл ..\src\binding.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\bui
ld\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\custom_function_bridge.h(5): f
atal error C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется и
сходный файл ..\src\custom_function_bridge.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modul
es\node-sass\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\custom_importer_bridge.h(5): f
atal error C1083: Не удается открыть файл включение: sass/functions.h: No such file or directory (компилируетс
я исходный файл ..\src\custom_importer_bridge.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_mo
dules\node-sass\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_context_wrapper.h(8): fat
al error C1083: Не удается открыть файл включение: sass/context.h: No such file or directory (компилируется ис
ходный файл ..\src\sass_context_wrapper.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\
node-sass\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\boolean.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sa
ss\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\color.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\error.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\factory.h(5): fatal
 error C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исход
ный файл ..\src\sass_types\factory.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-
sass\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\list.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\
build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\map.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\b
uild\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\null.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\
build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\number.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sas
s\build\binding.vcxproj]
  c:\users\neo\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\src\sass_types\value.h(5): fatal e
rror C1083: Не удается открыть файл включение: sass/values.h: No such file or directory (компилируется исходны
й файл ..\src\sass_types\string.cpp) [C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sas
s\build\binding.vcxproj]

```
0 Warning(s)
13 Error(s)
```

Time Elapsed 00:00:59.39
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Neo\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
C:\Users\Neo\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "harp"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
npm ERR! code 1

C:\WINDOWS\system32>**
How it correct ? 

_screens:_
![screenshot_25](https://cloud.githubusercontent.com/assets/21061543/17703087/212423c2-63d9-11e6-8f3b-31fee442be44.png)
![screenshot_26](https://cloud.githubusercontent.com/assets/21061543/17703086/21172370-63d9-11e6-9c96-ee268a0dabff.png)
![screenshot_27](https://cloud.githubusercontent.com/assets/21061543/17703140/526af06e-63d9-11e6-9579-25a61982beff.png)

**Comment by learntoswim** [comment]
Seeing the same errors. Looking for a fix. If I find one, I'll report back.

**Comment by pepopowitz** [comment]
I believe this is a similar issue, if not the same, as [#571] (https://github.com/sintaxi/harp/issues/571). Long story short, node-sass stopped working at some v6 release of NodeJs, and HarpJs is still depending on that older version. You can read much more in that issue, and some of the places it links to. 

If you don't really care what version of NodeJs you're running, you could revert to v4.5.0 to get Harp installed and running. 

If you aren't willing to completely downgrade your version of NodeJs to 4.5.0, a potential workaround for now would be to use a version manager like [nvm](https://github.com/creationix/nvm) for Mac/Linux, or [nvm-windows](https://github.com/coreybutler/nvm-windows) for Windows. This would allow you to switch between NodeJs versions easily - v4.5.0 when you want to run HarpJs, and v6.x when you want to do other things.

Hopefully that helps, if you haven't already discovered it yourself or moved on to something else.

**Comment by sintaxi** [comment]
@learntoswim @pepopowitz I'd be curious to know if this issue is now resolved with the publishing of `harp@0.23.0`. If you get the chance to test that would be really great.

**Comment by pepopowitz** [comment]
I was able to install v0.23.0 of Harp with v6.5 of node. Looks fixed to me! 😸 👍

**Comment by sintaxi** [comment]
Thanks for reporting. Closing ticket.

**Comment by bogdan-calapod** [comment]
I just tried installing harp and have the same errors, on Windows 10 and Node.js 7.5.0.

**Comment by sintaxi** [comment]
@bogdan-calapod thanks for reporting the issue. Will take a look.

FWIW - Harp targets the LTS release of node which I highly suggest all node users uses especially when on windows. If you're looking for a quick solution Id say switching to LTS is definitely the way to go.

**Comment by bogdan-calapod** [comment]
Indeed, switching to LTS works.
