### ISSUE TITLE
Stylus not compiling

### ISSUE THREAD

**Issue by wontron** [sintaxi/harp#576]
I'm running Harp v0.21.0, and I'm unable to compile a basic Stylus file. At first I thought it was an issue with an @import, but my current main.styl to test with is just:

```
body
   color green
```

In my public/_layout.jade, I include:
`link(rel="stylesheet", type="text/css", href="/assets/css/main.css")`

The error message appears at the top of my page as a body::before element with yellow background-color. Any change that is saved will first print the error: 
`"Stylus -> CSS (Path must be a string. Received undefined) /path/to/main.styl"`
and in Terminal (running `harp server`):

```
{ body
  color green
  filename: '/path/to/main.styl',
  lineno: 2,
  source: 'Stylus',
  dest: 'CSS',
  name: 'Stylus Error' }
```

Any refresh of the page after that will print:
`"Stylus -> CSS () /path/to/main.styl`
and in Terminal:

```
{ body
  color green
  filename: '/path/to/main.styl',
  lineno: NaN,
  source: 'Stylus',
  dest: 'CSS',
  name: 'Stylus Error' }
```

I have Stylus installed globally as well, and if I run `stylus -w /path/to/main.styl`, it compiles to main.css and Harp is able to include that correctly (i.e. it reads the compiled main.css instead of looking for main.styl to compile, and all body text appears green).

Any ideas on what's going on? Thank you!

**Comment by jaubut** [comment]
#same error here

**Comment by sethwhitton** [comment]
Suffering with this error as well
