### ISSUE TITLE
Harp is not serving js files from public directory.

### ISSUE THREAD

**Issue by atularvind** [sintaxi/harp#581]
I am trying to compile my app on harp js. here is my directory structure.
```
.
├── 404.html
├── _harp
│   ├── 404.jade
│   ├── _data.json
│   ├── _harp.json
│   ├── _layout.jade
│   ├── index.jade
│   ├── main.less
│   └── public
│       ├── css
│       │   ├── bootstrap.css
│       │   ├── font-awesome.min.css
│       │   ├── hoverex-all.css
│       │   ├── prettyPhoto.css
│       │   └── style.css
│       └── js
│           ├── bootstrap.min.js
│           ├── custom.js
│           ├── jquery.hoverdir.js
│           ├── jquery.hoverex.min.js
│           ├── jquery.isotope.min.js
│           ├── jquery.prettyPhoto.js
│           ├── modernizr.min.js
│           └── retina-1.1.0.js
├── index.html
├── main.css
└── public
    ├── css
    │   ├── bootstrap.css
    │   ├── font-awesome.min.css
    │   ├── hoverex-all.css
    │   ├── prettyPhoto.css
    │   └── style.css
    └── js
```

now when i try to compile the app using
`harp compile _harp ./`

It is not compiling the js in the js directory. the js directory is always blank. I have checked the permission it seems everything what I am missing?

**Comment by matthiaskjordan** [comment]
Your directory is all kinds of screwy. Try to set up something like this: 

```
.
├── harp.json
├── license.txt
├── package.json
└── public
    ├── _data.json
    ├── _layout.ejs
    ├── assets
    │   ├── css
    │   │   └── main.css
    │   └── js
    │       └── app.js
    └── index.ejs
```

**Comment by iammatthias** [comment]
Your directory is all kinds of screwy. Try to set up something like this: 

```
.
├── harp.json
├── license.txt
├── package.json
└── public
    ├── _data.json
    ├── _layout.ejs
    ├── assets
    │   ├── css
    │   │   └── main.css
    │   └── js
    │       └── app.js
    └── index.ejs
```

**Comment by atularvind** [comment]
@iammatthias tried something like you explained, but still the js directory is empty.

**Comment by iammatthias** [comment]
What does your directory look like now?

**Comment by frank-dspeed** [comment]
i can make it short for you guys harp is realy not serving js files right even in my fork i think the problem has something to do with terraform and the coffescript parsing. 

but i do a complet rewrite at present to make it all work and even more.

**Comment by atularvind** [comment]
@frank-dspeed so it is not possible? any workaround?

**Comment by frank-dspeed** [comment]
atularvind current workaround is to use static('./dir'), harp.mount('./dir') in a express or connect app
and implament own logic for static to only serve js files

**Comment by iammatthias** [comment]
@atularvind it is definitly possible. I build and deploy my site using Harp multiple times a week. No issues with JS.

What version of Node are you running? I had some issues with Node v6.*.*, but everything functions properly now that I rolled back to v4.6.0

Do you have a link to the repo so I can take a look?

**Comment by iammatthias** [comment]
Okay, @atularvind. I cloned the repo for your site. You need to run `harp compile` from inside your `_harp` directory. This will compile properly into a directory called `www`.

**Comment by sintaxi** [comment]
Hey all, I think we are ready to cut a new release of harp provided this is not an issue so please report your findings if you debug this further. Be sure to update to the latest topic release by `npm install -g harp@next`. Thanks for all your help.

**Comment by atularvind** [comment]
@iammatthias Thank you, I am referring same page for guidance, for a workaround I removed the static js files from my .jade templates and loaded js files from cdn. 

@sintaxi yes, I also think so that should not be the issue but something I am missing. I will surely report my findings.

Thanks!

**Comment by sintaxi** [comment]
@atularvind & @frank-dspeed do you mind checking your version of harp for me?

**Comment by atularvind** [comment]
yes, right now my system contains v0.20.3.

**Comment by frank-dspeed** [comment]
@sanitax where is the repo for harp@next?

**Comment by iammatthias** [comment]
@frank-dspeed I'd assume it's v0.21.0-pre branch: https://github.com/sintaxi/harp/tree/v0.21.0-pre

@sintaxi is that correct?

**Comment by sintaxi** [comment]
@iammatthias @frank-dspeed correct

**Comment by atularvind** [comment]
@sintaxi newer version resolves the issue with serving js files from public directory.
I have upgrade the harp using to version **0.21.0-pre.1**
`sudo npm install -g harp@next`

@iammatthias @frank-dspeed @sintaxi Thanks a lot for the help!
