### ISSUE TITLE
running harp with pm2?

### ISSUE THREAD

**Issue by dcsan** [sintaxi/harp#585]
anyone have experience starting a harp server with pm2?

is there a simpler way to start the server just as a node app, or do i have to use its own `harp server` command?

**Comment by dcsan** [comment]
or otherwise how are people running this in production?

**Comment by matteo-bombelli** [comment]
Hello!

as suggested here: https://github.com/sintaxi/harp

```javascript
var harp = require("harp")
harp.server(projectPath [,args] [,callback])
```

**Comment by matteo-bombelli** [comment]
You can also use it with expressjs (I'm using it in development for now... hopefully will switch to prod)

```javascript
app.use(express.static(__dirname + "/public"));
app.use(harp.mount(__dirname + "/public"));
```
