### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by jacobtarr** [sintaxi/harp#588]
There appears to be an issue running the latest version of Harp. I'm not sure if this is just me, but I made sure I was up-to-date on everything and I'm getting an unhandled promise rejection warning and it appears to be an issue with autoprefixer and browserslist. Message below: 

`(node:4408) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): BrowserslistError: Unknown browser query `op_mini all`
(node:4408) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by priyalollypop** [comment]
Hey,

Even i am facing this problem. any solution..?

Thanks in Advance

**Comment by remy** [comment]
I had the same problem and managed to find the source of the issue. Unsure if I can do a PR fully into terraform (a dep of harp) because it's a major bump in autoprefixer.

However, the fix (for me) was to remove a `@supports` check in my CSS. Not ideal, but it would build now. Your milage may vary!

**Comment by sintaxi** [comment]
How needed is autoprefixer at this point. Anyone know?

**Comment by ccprog** [comment]
My take is that the autoprefixer uses the data from caniuse via https://github.com/ben-eb/caniuse-lite. This db is up-to-date, so you get the prefexis that you need.

In my case, box-shadow, flex, transition and animation had prefixes, and for all of them I found corresponding caniuse entries with usages > 0%. So using them makes sense.

For me, updating to autoprefixer 7.1.2 worked.
