### ISSUE TITLE
Feature Request: Pre-compile hooks to wire in Grunt, Gulp, Brocolli, etc. where desired

### ISSUE THREAD

**Issue by jfrux** [sintaxi/harp#589]
It should have pre-compile hooks.

Maybe just a directory or a particular initializer folder outside of public that doesn't get compiled for JS logic that needs to run prior to compiling.

Could use it to do a simple concat of all of the JS, etc.

Then you wouldn't have to worry about people wanting this functionality and they could do it all themselves if they desire it.

Ideally, these pre-compile hooks would work in both server mode and compile mode.

I'd love to be able to link to a single "app.js" for instance and have it "just work" because my pre-compile hook has taken care of that by compiling everything.

**Comment by matteo-bombelli** [comment]
I've used it in a different way:

gulp with: 

```javascript
var harp = require("harp")
harp.compile(projectPath [,outputPath] [, callback])
```
