### ISSUE TITLE
Path must be a string. Received undefined.

### ISSUE THREAD

**Issue by jaubut** [sintaxi/harp#590]
Even the simplest styl files will come up with that error.. 

H1 
      color blue

**Comment by sintaxi** [comment]
- what does the error look like?
- how do I recreate it?
- what is your version of harp?
- what is your version of NodeJS?
- what OS are you on?

**Comment by jaubut** [comment]
Its either when i try to see it with harp server command. I just Factory
reset my mac so i reinstalled harp from the ground up, same for node. And
im on MacSerria

**Comment by sintaxi** [comment]
Thanks for the additional info. I just published `harp@0.23.0` do mind seeing if that clears up the issue?

**Comment by jaubut** [comment]
Nop.. didn’t work for me..
