### ISSUE TITLE
RSS not being excluded from Layout

### ISSUE THREAD

**Issue by magician03** [sintaxi/harp#591]
The RSS is not being excluded from Layout even after mentioning in `_data.json` file about exclusion as shown below. Have tried both jade and EJS formats. Not Working in both.

```
{
	"rss": {
		"layout": false
	}
}
```

**Comment by adamfr33man** [comment]
I'm also having the same problem on a site that I built about a year ago. This used to work but now it puts the layout around my sitemap

**Comment by adamfr33man** [comment]
Actually, turns out for me it seems I need to update the sitemap to be sitemap.xml as my file is named sitemap.xml.ejs. @magician03 perhaps try changing yours to "rss.xml" ?

`{
	"sitemap.xml": {
		"layout": false
	}
}`

I'm ok with this, but it means this page is now misleading:
https://harpjs.com/recipes/blog-sitemap

**Comment by jorgepinon** [comment]
I thought I had the same problem but then I realized that I had
```
"sitemap" : {
    "layout": false
}
```
where it should have been
`"sitemap.xml"`

However I do see that @adamfr33man does have the trailing .xml in his example.

**Comment by benpetersen** [comment]
Thank you @jorgepinon and @adamfr33man, I've been searching for this for a while! Currently

**Comment by Xixiao007** [comment]
Thank you folks above... I have been debugging for one night and reached here...
