### ISSUE TITLE
JS files not copied on compile

### ISSUE THREAD

**Issue by mobinni** [sintaxi/harp#593]
I have an odd error:

When I run harp server, everything runs perfectly, however when I run harp compile not all files referenced als links or scripts are copied to the www/ folder. It seems to be that it compiles the css correctly from the styles folder, but JS files and css files from other folders are not copied.

Any idea why this would happen?

Configuration:

harp 0.23
node 6.0.0

Currently I have copy task that fills in the blanks.

**Comment by sintaxi** [comment]
Hmm. Are you able to send over a project that demonstrates the issue?

**Comment by mobinni** [comment]
Yeah, it's here
https://github.com/rangle/augury.angular.io

**Comment by sintaxi** [comment]
great thanks! are you on *nix or windows?

**Comment by mobinni** [comment]
Mac

**Comment by erkkit** [comment]
I also have this issue with 0.21.0-pre.1. Compiling also ignored images folder in my case.

Here's the compile.sh script I created as a workaround.

```
harp compile
cp -a img/ www/img
cp -a js/ www/js
```

**Comment by misterhtmlcss** [comment]
@mobinni  how are things going? Are you still stuck here? We kind of disappeared there for a while, but we are back now and trying to learn who's issues are aged out and which ones are still current. Anything a year old will get closed first, but that doesn't mean your concerns are unwelcome; just that we need a new Issue to be opened.

Have a great week! Let us know if we can assist you further via a new Issue.
