### ISSUE TITLE
Error in less.js when running harp compile

### ISSUE THREAD

**Issue by herkyl** [sintaxi/harp#595]
I'm getting this error from `less.js` when running `harp compile`. I'm using `nvm` and tried other node versions, all get the same error. `Harp server` works fine.

```
/Users/serge/.nvm/versions/node/v6.2.0/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/less.js:25
      return callback(null, css.css, css.map.toString())
                                            ^

TypeError: Cannot read property 'toString' of undefined
  at /Users/serge/.nvm/versions/node/v6.2.0/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/less.js:25:45
  at /Users/serge/.nvm/versions/node/v6.2.0/lib/node_modules/harp/node_modules/less/lib/less/render.js:35:17
  at /Users/sergeherkul/.nvm/versions/node/v6.2.0/lib/node_modules/harp/node_modules/less/lib/less/parse.js:63:17
  at Object.finish [as _finish] (/Users/serge/.nvm/versions/node/v6.2.0/lib/node_modules/harp/node_modules/less/lib/less/parser/parser.js:183:28)
  at Object.ImportVisitor._onSequencerEmpty (/Users/serge/.nvm/versions/node/v6.2.0/lib/node_modules/harp/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
  at ImportSequencer.tryRun (/Users/se%       
```

**Comment by oakland** [comment]
I have the same problem with you, and my OS is windows 7, node-version is 6.9.4. There will be an empty asset folder after compiling, so I have to copy all the js, css, and pictures into the www folder and place them into the correct location. Hope somebody can help.

**Comment by sandravu** [comment]
I ran into the same thing while compiling:
TypeError: Cannot read property 'toString' of undefined
  at /usr/local/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/less.js:25:45
  at /usr/local/lib/node_modules/harp/node_modules/less/lib/less/render.js:35:17
  at /usr/local/lib/node_modules/harp/node_modules/less/lib/less/parse.js:63:17
  at Object.finish [as _finish] (/usr/local/lib/node_modules/harp/node_modules/less/lib/less/parser/parser.js:183:28)

node v6.9.4, OS Mac El Capitan

**Comment by herkyl** [comment]
What I did was convert all of my LESS code to SASS, I know it's a lousy fix but works for now

**Comment by maiduchuy** [comment]
I'm having the same issue on windows 10, nodejs 6.9.5, npm 5.0.3.

**Comment by akehsanz** [comment]
why man why??
Still the problem persists in Aug 2017?
I'm also facing same issue on Win7 x64, nodejs 6.11.0 npm 3.10.10

**Comment by benpetersen** [comment]
I think this is related to terraform node-sass update. After uninstalling harp and reinstalling it, I'm still having issues using node version 6.10.3 and npm version 4.4.4
The version his packages were using were node 8.0.0  and npm 5.0.1

**Comment by marykatefain** [comment]
I had this same issue, but it only applied to empty .less files. As soon as I filled them with styles it worked. I think this is just a bug that doesn't know what to do with an empty .less file. Are people seeing this with files that contain styles?

**Comment by sintaxi** [comment]
@benpetersen @marykatefain thanks so much for the help. An empty `.less` files was causing the sourcemap to break. https://github.com/sintaxi/terraform/commit/63a0c7dd41c5afb933944db5cdb23ca710fbfb8d

A release of `harp@0.24.1` fixes the issue.
