### ISSUE TITLE
should support Handlebars

### ISSUE THREAD

**Issue by sintaxi** [sintaxi/harp#60]
- should have the extension `.hbs`.

**Comment by veryangrymobster** [comment]
+1 Handlebars support would be great.

**Comment by isaacrg** [comment]
:+1: Would be awesome.

**Comment by bparonto** [comment]
👍 yes please

**Comment by bjankord** [comment]
:+1:

**Comment by gillesdemey** [comment]
Is this being worked on or still considered? I might take a stab at this and implement it in terraform.

**Comment by kennethormandy** [comment]
@gillesdemey We have an open pull request for it https://github.com/sintaxi/terraform/pull/93 but haven’t merged it yet. Browserify support is still our next planned release.

**Comment by cfjedimaster** [comment]
Is there anything we can do to help get the PR in? Like testing of any
sort.

**Comment by sintaxi** [comment]
> Is there anything we can do to help get the PR in?

Something is still unclear to me. What does handlebars do which isn't already provided by ejs? How does handlebars improve harp?

**Comment by cfjedimaster** [comment]
Well you can make the argument that one template language  is all you need.
:) At the end of the day though supporting Handlebars is about providing
more choices for users.  Imo,  Handlebars is just plain nicer to use than
EJS.

If there is any grunt work I can do to make this happen I will.

**Comment by cfjedimaster** [comment]
I hit send before boarding a plane - as part of the grunt work, I'd be
happy to help update the core docs for the site.

On Thu, Aug 27, 2015 at 10:43 AM, Raymond Camden <raymondcamden@gmail.com>
wrote:

> Well you can make the argument that one template language  is all you
> need. :) At the end of the day though supporting Handlebars is about
> providing more choices for users.  Imo,  Handlebars is just plain nicer to
> use than EJS.
>
> If there is any grunt work I can do to make this happen I will.
> On Aug 27, 2015 8:40 AM, "Brock Whitten" <notifications@github.com> wrote:
>
>> Is there anything we can do to help get the PR in?
>>
>> Something is still unclear to me. What does handlebars do which isn't
>> already provided by ejs? How does handlebars improve harp?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sintaxi/harp/issues/60#issuecomment-135197653>.
>>
>


-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by kennethormandy** [comment]
Honestly, most of that is done on a branch already too https://github.com/harp/harpjs.com/tree/ko-handlebars

**Comment by earth2marsh** [comment]
:+1:

**Comment by sidonaldson** [comment]
If it's a quick win then why not?

**Comment by isaacrg** [comment]
@sintaxi @kennethormandy 
What is the status of sintaxi/terraform#93? Is it ready to go ahead?

**Comment by szines** [comment]
I'm really looking forward the handlebar support. Hope will be released soon. ;) Keep up the good work.

**Comment by n400** [comment]
Looking forward to this as well because I have a handlebars site I want to move to harp

**Comment by openhoat** [comment]
:+1:

**Comment by MeanwhileMedia** [comment]
+1

**Comment by gabskoro** [comment]
It's almost three years now after the issue was opened, what are we waiting for?

**Comment by caillou** [comment]
@sintaxi wrote:

> Something is still unclear to me. What does handlebars do which isn't already provided by ejs? How does handlebars improve harp?

In my particular case, I would like to port a legacy project to harp.js. The project uses twig templates. If harp.js would offer the possibility to use other templating-engines, such a port would be much simpler.
