### ISSUE TITLE
When update HarpJS?

### ISSUE THREAD

**Issue by Xyroqs** [sintaxi/harp#607]
1. When update HarpJS?
2. Is it possible to add a function to compile to a PHP version with active PHP code?

**Comment by insanetisane** [comment]
An update would be nice. For any interested there's a similar tool to harp called [Pingy](https://pin.gy/cli/). New and a bit more modern (support for Babel etc..) but no markdown support so far I think.

As for the PHP question I highly doubt that will happen or even makes sense. Harp is a static site generator. PHP is a server side language.

**Comment by misterhtmlcss** [comment]
@Xyroqs sorry at this time it's unlikely this type of request will be something we'll consider. But we thank you for taking the time and also our not taking action doesn't mean your request isn't informative for future consideration. 

Come back with more Issues soon!
