### ISSUE TITLE
problem upgrading harp -- node-sass

### ISSUE THREAD

**Issue by jaubut** [sintaxi/harp#612]
Hi, anyone encounter problems with node-sass while upgrading harp to the latest version.. I try many times to uninstall harp completely and then retry both on node 8.x and node@6.. both doesnt work at all.. 

On my terminal when I try with node 8 : gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.1.3' ]
gyp verb install input version string "8.1.3"
gyp verb install installing version: 8.1.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.3
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/harp/node_modules/node-sass/.node-gyp/8.1.3
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/harp/node_modules/node-sass/.node-gyp/8.1.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/harp/node_modules/node-sass/.node-gyp"

**Comment by jaubut** [comment]
And it goes on and on and on.. until I hit Ctrl - C..

**Comment by htulibacki** [comment]
@jaubut try this:

`sudo npm install -g harp --unsafe-perm`

**Comment by jaubut** [comment]
Thanks it works 👍
