### ISSUE TITLE
Error when trying to initialize Harp

### ISSUE THREAD

**Issue by blaineb** [sintaxi/harp#618]
When trying to initialize my first project after installing harp, I'm getting this:

fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/harp/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

**Comment by CharlesKumar** [comment]
I got this problem while installing 

node v 9.1.0

npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
C:\Users\Charlie\AppData\Roaming\npm\harp -> C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\bin\harp

> node-sass@4.5.3 install C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files (x86)\Python36-32\python.EXE
gyp verb check python version `C:\Program Files (x86)\Python36-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.1\r\n"
gyp verb could not find "C:\Program Files (x86)\Python36-32\python.EXE". checking python launcher
gyp verb could not find "C:\Program Files (x86)\Python36-32\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files (x86)\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
gyp ERR! node -v v9.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\are-we-there-yet\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\Charlie\AppData\Roaming\npm\node_modules\harp\node_modules\are-we-there-yet\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\are-we-there-yet\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\Charlie\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\are-we-there-yet\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Charlie\AppData\Roaming\npm-cache\_logs\2017-11-13T14_14_03_561Z-debug.log
