### ISSUE TITLE
404 file

### ISSUE THREAD

**Issue by jerickBilalat** [sintaxi/harp#619]
Can not compile when 404.ejs/md/jade is in the root but instead gives a reference error with a message saying myVariable is not defined. The myVariable is defined in _data.json which also at the root. If I change the file format to 404.html then it compiles or if I delete the 404 file. This is a problem if one is planning on using variables in the 404 page and needs a ejs, md, or jade template.

**Comment by misterhtmlcss** [comment]
Have you over come this issue? This would seem to be a significant problem that we need to address if you still find this issue, reopen a new issue and we'll investigate. Thank you for submitting this issue!
