### ISSUE TITLE
Disable layout for XML no longer works

### ISSUE THREAD

**Issue by omichelsen** [sintaxi/harp#628]
I have a sitemap.xml.jade file and in `_data.json` I have the following lines:
```json
"sitemap": {
    "layout": false
},
```
This have been working great since I started using Harp, but now it stopped working. It will add the default layout template to the top of my XML file, and thus making it unreadable/invalid.

I didn't change anything in my source files, only upgraded Harp to the latest version (v0.25.0).

**Comment by MartyO256** [comment]
Try adding the extension to the file name if you have a `sitemap.xml.jade` file:
```
"sitemap.xml": {
    "layout": false
},

**Comment by omichelsen** [comment]
That did the trick - thanks! 👍

**Comment by Pectojin** [comment]
This does not seem intentional. The documentation seems very explicit about this being supposed to work without the extension.

http://harpjs.com/docs/development/layout#no-layout
