### ISSUE TITLE
Request : Auto Reload

### ISSUE THREAD

**Issue by jm-kumaresh** [sintaxi/harp#629]
Any idea adding auto reload the browser when there is a changes in file.

**Comment by omichelsen** [comment]
You can do it with [browser-sync](https://ole.michelsen.dk/blog/using-browser-sync-with-harp.html).

**Comment by Nadeeshyama** [comment]
I use [livereladx](https://github.com/nitoyon/livereloadx). Example `package.json` file:

```javascript
"scripts": {
    "server": "harp server",
    "livereload": "livereloadx -s public --include '*.{json,less,scss,js,ejs,jade,md,pug}'",
    "dev": "npm-run-all --parallel server livereload",
    "start": "npm run dev",
    "compile": "harp compile"
}
```

**Comment by misterhtmlcss** [comment]
@omichelsen Thank you for sharing that article. Also @Nadeeshyama that's a great set up you have for your package.json as well. Thank you guys.
