### ISSUE TITLE
Harpjs.com

### ISSUE THREAD

**Issue by silentrob** [sintaxi/harp#641]
Just renewed the domain for another year. Harp is now over 7 years old. This is just a FYI.

**Comment by herkyl** [comment]
Glad to see Harp becoming active again. This is the only static site generator that "just works".

**Comment by sintaxi** [comment]
@silentrob thanks bud! Yeah, 7 years is quite a milestone.

@herkyl Indeed. All thanks to @misterhtmlcss for blowing off the dust.
