### ISSUE TITLE
EJS in readme links to embeddedjs.com which is now an advertisment for an online gambling site

### ISSUE THREAD

**Issue by nilsgawlik** [sintaxi/harp#649]
I'm not familiar with the project, but while reading through the readme I clicked on EJS in the table of supported pre-processors and it took me to embeddedjs.com. 
This URL seems to have been bought up and is now just an advertisement for an online gambling site (a scam probably).

So it would be good to change that link to something else, to not be affiliated with stuff like that.

**Comment by hisyam** [comment]
#653

**Comment by sintaxi** [comment]
Fixed.
