### ISSUE TITLE
Harp Platform TLS cert invalid

### ISSUE THREAD

**Issue by berezovskyi** [sintaxi/harp#656]
http://harpjs.com/docs/deployment/harp-platform

![image](https://user-images.githubusercontent.com/64734/68223281-cab90a80-ffec-11e9-8c81-70ba86761641.png)

Also, the `www` subdomain does not have a correct A record.

**Comment by sintaxi** [comment]
fixed. thanks. 
<img width="490" alt="Screen Shot 2019-11-07 at 5 30 41 PM" src="https://user-images.githubusercontent.com/867/68441881-5c0eb500-0184-11ea-90bd-46d154fcd32d.png">
