### ISSUE TITLE
Doesn't work with Node version > 12

### ISSUE THREAD

**Issue by jodymgustafson** [sintaxi/harp#670]
When I try to run harp I get the following error:

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)

This is because node sass only works with node up to version 12. Even if I remove any sass files it still throws this error. This makes Harp unusable for me since I'm on v14. I can live without sass support. Is there any way to tell Harp to not use the sass processor so the whole thing isn't broken?

**Comment by jodymgustafson** [comment]
Never mind. I figured out that I had an old version of harp installed globally.

**Comment by sintaxi** [comment]
I figured that was the case. To be sure I just make a release which updates all the dependencies. `harp@0.41.2`
