### ISSUE TITLE
Light theme friendly Harp logo?

### ISSUE THREAD

**Issue by ericapisani** [sintaxi/harp#674]
Hi folks!

The Netlify team is hoping to use the Harp logo as part of some enhancements we're making to the [framework detection utility](https://github.com/netlify/framework-info/) that we maintain, and unfortunately for folks using a light theme, the logo can be a bit difficult to see.

I'm wondering if it's possible to get a light theme friendly Harp logo for us to use within the utility (ideally as an SVG).

Thanks in advance!

**Comment by matteo-bombelli** [comment]
hello, 
not sure if that is what you need but maybe you can look in here http://harpjs.com/identity/ for trademarks

**Comment by ericapisani** [comment]
What you linked is perfect, thank you!
