### ISSUE TITLE
MISSING INIT FILE 'ERROR'

### ISSUE THREAD

**Issue by FrontEndProfile** [sintaxi/harp#680]
![image](https://user-images.githubusercontent.com/102220108/212297294-65a4137b-e702-4dee-be01-4556e20b3f81.png)

**Comment by sintaxi** [comment]
I was able to get that project working by running the following....

```
git clone git@github.com:kennethormandy/hb-remedy.git
cd hb-remedy
npm init -y
npm install -g harp
npm install less --save-dev
harp .
```

<img width="1531" alt="Screenshot 2023-01-13 at 2 28 57 AM" src="https://user-images.githubusercontent.com/867/212298250-6244c5f6-535d-4478-9db6-5339bfef820e.png">
