### ISSUE TITLE
Provide source maps where available

### ISSUE THREAD

**Issue by silentrob** [sintaxi/harp#74]
Harp should support source maps where available.
http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

This is landing in Less 1.5 
https://github.com/less/less.js/issues/1050

CoffeeScript 1.6
TypeScript supports it

Jade has an issue, but...
https://github.com/visionmedia/jade/issues/941

This boils down to generating a second file and referencing it via header.

**Comment by crswll** [comment]
+1

**Comment by amitkeret** [comment]
+1

**Comment by davej** [comment]
Hate to just tack on a +1. I tried Harp and love the simplicity but source maps is the feature which prevents me from switching from Gulp.

**Comment by og2t** [comment]
Same here. Minification of JS and CSS without source maps doesn't work when you need to debug ;-)

**Comment by tjnicolaides** [comment]
Just wanted to run this terraform PR past the group to see if I'm on the right path before implementing in the harp project, too.

Once I get into Harp, I'm struggling between the following two choices:

1. Should sourcemaps be ON or OFF by default, with a config option to toggle? Or, if they're available for a particular file extension, are they always ON?
1. Should users have a config option to change which directory maps get written to, with the default being the same directory as the minified CSS/JS? Or are should they always be written to the same directory?

Once we have the .scss maps proofed out, would we finish adding .less/.styl maps to terraform.git, or all available sourcemapped extensions, or just roll out the one for harp.git?

**Comment by kennethormandy** [comment]
@sintaxi will have the final word on this, but my expectation would be:

1. On by default for all preprocessors (regular HTML, CSS, and JS goes through a different codepath right now) in development environments (ex. `harp server) but not in production environments (ex. `harp compile`, or when using Harp as middleware)
2. Source maps should be served and updated on each request, but not written to the file system, which is how the preprocessors already work.

Our goal would be to have them for all preprocessors, but we wouldn’t be opposed to starting with Sass and tagging a release of Terraform, if that was significantly easier.

**Comment by davej** [comment]
By the way, I ended up writing my own middleware that compiles the usual suspects (sass, less, stylus, coffeescript, babel, etc..) and does sourcemaps too: https://github.com/davej/piggy-in-the-middle

**Comment by tjnicolaides** [comment]
Ok Harp team, please have a look at the sourcemap pull requests I've opened in Harp and Terraform and advise on how you'd like to see them improved in order to be accepted. Our dev team makes heavy use of Harp and we're really looking forward to making use of `*.scss` sourcemaps in 2016. Thanks!

**Comment by stephenhowells** [comment]
Any movement on this topic? In 2016 source maps are compulsory to front end development. I'd love to see this discussion pick up again.

**Comment by peterwilli** [comment]
This is a bit of a bummer :( I just really fell in love with Harp when I found out that my coffeescripts doesn't have source maps mapped to their minified JS counterparts :(

**Comment by og2t** [comment]
+1
